### ISSUE TITLE
Account activities tab

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#10]
Columns:
- Hash: in some cases we won’t have any tx-hash, e.g. AENS expiration won’t have any tx-hash, the same for Beneficiary reward
- Date
- Type
- Activity
- Data

Type | Activity | Data | Technical considerations
-- | -- | -- | --
AE | Transferred toReceived fromBeneficiary reward | ak_… + Æ amountak_… + Æ amountÆ amount | how to deal with SH-DEX activities to avoid duplications?
AENS | ClaimedExpiredRevokedReceived fromTransferred to | xyz.chainxyz.chainxyz.chainak_… + xyz.chainak_… + xyz.chain |  
AEX-9 | Token createdTransferred toReceived fromMint receivedBurned | TOKEN_SYMBOLak_… + TOKEN_SYMBOL & amountak_… + TOKEN_SYMBOL & amountTOKEN_SYMBOL & amountTOKEN_SYMBOL & amount | how to deal with SH-DEX activities to avoid duplications?can we distinguish transfers, mints and burns?
AEX-141 | Collection createdTransferred toReceived fromMint receivedBurned | COLLECTION_NAMEak_… + COLLECTION_NAME & nft_idak_… + COLLECTION_NAME & nft_idCOLLECTION_NAME & nft_idCOLLECTION_NAME & nft_id | can we distinguish transfers, mints and burns?
SH-DEX(to be checked) | SwappedAdded liquidityRemoved liquidity | TOKEN_SYMBOL & amount ↔︎ TOKEN_SYMBOL & amountTOKEN_SYMBOL & amount +TOKEN_SYMBOL & amount ↔︎ POOL_SYMBOL & amountPOOL_SYMBOL ↔︎ TOKEN_SYMBOL & amount + TOKEN_SYMBOL & amount | see AE and AEX-9 comments, avoid duplicated outputmaybe we need to include that in the type “AEX-9” and cannot have it separately in SH-DEX as type
? | ? | ? | ?

<p></p>

Endpoint: GET /v2/accounts/:id/activities

**Comment by marc0olo** [comment]
@lukeromanowicz @michele-franchi I just provide the screenshot here for better readability:

![image](https://github.com/aeternity/aescan/assets/8124114/ee407735-c69a-4133-84df-6d9408ffafa0)

**Comment by lukeromanowicz** [comment]
@marc0olo would you be able to provide accounts where the mentioned activities happened?

**Comment by lukeromanowicz** [comment]
Looks like we need to simplify Contract-related fields due to insufficient information available in mdw. Here is a mdw issue to track:
https://github.com/aeternity/ae_mdw/issues/1497

**Comment by lukeromanowicz** [comment]
Other (non-blocking) related issue that has been reported: https://github.com/aeternity/ae_mdw/issues/1498

**Comment by davidyuk** [comment]
> the same for Beneficiary reward

the block hash may be used instead. Also, consider showing reward transfers to BRI account.

**Comment by marc0olo** [comment]
> the block hash may be used instead

if we do that I would prefer to include the block hash in "data" column 😅 


> Also, consider showing reward transfers to BRI account.

yes, absolutely! but this is only relevant for one specific account IMO (or in the future for another BRI account in case that changes) @michele-franchi

**Comment by michele-franchi** [comment]
DEX contract: https://github.com/aeternity/dex-contracts-v2#on-mainnet
