### ISSUE TITLE
Handle not found pages

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#106]
Users may enter an entity details page with a wrong id put into the parameter. 

For example someone could directly type an invalid contract id like this:
https://aescan.dev.aepps.com/tokens/ct_J3zBY8xxjsRr3QojETNw48Eb38fjvEuJKkQ6KzECvubvEcvAE

The solution could simply be to redirect the user to a 404 not found page but we need a design for it.

Every page should be specific to the entity.

**Comment by danilosierrac** [comment]
Hi! Nice. Wouldn't this apply to the "Search not found" design we already have? Or do you want to show something inside the table that says a new type of message? I would go for a normal "search not found" in this case.

**Comment by michele-franchi** [comment]
@danilosierrac I see it a bit differently, in the search not found page we display the following:


![Image](https://github.com/aeternity/aescan/assets/11598532/86ab6cdb-0e80-4f2d-b997-63bbe6d4e5b6)


But it does not really look like a 404 page.

**Comment by danilosierrac** [comment]
I see. The 404 should look closer to the design of the 500 we are making, but this style in my opinion is good for things specifically that aren't found. Or do yo uwant also a prettier message with lightweight fun as well for this?
