### ISSUE TITLE
Account - Adjust transactions tab display only transactions performed by the account

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#11]
This should be implemented after https://github.com/aeternity/aescan/issues/10.

Account activities tab should be the default first tab.

**Comment by michele-franchi** [comment]
According to the middleware, it should be possible to do so with `owned_only=true&type=transactions`

**Comment by marc0olo** [comment]
that's cool, didn't know that! 👍

**Comment by lukeromanowicz** [comment]
Note: After implementing this change the account part is not needed anymore in the data column of account transactions since we know exactly who performed it.

To check: can we filter the tx count by `owned_only=true&type=transactions`, otherwise we lose the possibility to show tx count

**Comment by marc0olo** [comment]
> To check: can we filter the tx count by `owned_only=true&type=transactions`, otherwise we lose the possibility to show tx count

IMO this would anyway be wrong if tx count includes other tx's than those executed by the account itself. but this is probably matter of intepretation, too.

**Comment by lukeromanowicz** [comment]
@michele-franchi it's possible to display transactions only performed by a given account by switching:

```
      transactionsUrl.searchParams.append('account', accountId)
```
into
```
      transactionsUrl.searchParams.append('sender_id', accountId)
```

in accountDetails store, but it's not possible to get the count of transactions filtered only by sender_id. I talked with Sebastian from MDW team and they are not planning to add such a feature anytime soon as it requires a lot of work to implement. Should we continue considering it introduces some minor functionality regression?
