### ISSUE TITLE
Highlight detail IDs

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#111]
IDs should be more visible, as it is the most important information on the page. Now it has very low contrast.
![image](https://user-images.githubusercontent.com/11598532/232490583-9e6c0a68-bbea-4dee-9948-2629183f1539.png)

Suggested by @janmichek

**Comment by janmichek** [comment]
The proximity and hierarchy of information still does not feel right, even if we darken the background.
We can still do it as a first step, but something like this would improve the visual orientation
https://tronscan.org/#/address/THPvaUhoh2Qn2y9THCZML3H815hhFhn5YC

**Comment by michele-franchi** [comment]
This is fixed.
