### ISSUE TITLE
Move time calculation to MDW

### ISSUE THREAD

**Issue by janmichek** [aeternity/aescan#114]
### Context information
Some adapters are using block height to calculate time, But some needs to be calculated because there is no time entry in response

### Steps to reproduce

see usage formatBlockDiffAsDatetime in [adapters.js](https://github.com/aeternity/aescan/blob/develop/src/utils/adapters.js)

### What is expected?

Move other calculations to backend, remove `formatBlockDiffAsDatetime()` then

This Issue is followup of https://github.com/aeternity/aescan/issues/100

MDW Tracking https://github.com/aeternity/ae_mdw/issues/831

**Comment by janmichek** [comment]
It's solved on MDW side now, ready to implement on our side

**Comment by janmichek** [comment]
Followup Tracking
https://github.com/aeternity/ae_mdw/issues/1425

**Comment by michele-franchi** [comment]
The followup is ready to be implemented.

**Comment by janmichek** [comment]
It's only partly fixed  here https://github.com/aeternity/aescan/pull/489 as some values from MDW are missing. So this issue should not be closed and needs further adjustment

https://github.com/aeternity/ae_mdw/issues/1425#issuecomment-1701006129

https://github.com/aeternity/ae_mdw/issues/1425#issuecomment-1700994875

**Comment by janmichek** [comment]
last 2 values are fixed on mdw side, waiting for deployment

**Comment by janmichek** [comment]
It still has not been developed. Pinged again

**Comment by michele-franchi** [comment]
@janmichek to check if it's fixed or something is still missing

**Comment by janmichek** [comment]
Still not fully resolved.
Status: https://github.com/aeternity/ae_mdw/issues/1425#issuecomment-1880384717
