### ISSUE TITLE
Explain token events Name and Data

### ISSUE THREAD

**Issue by janmichek** [aeternity/aescan#132]
### Please describe the problem that your request should resolve.
Explain why is `Name` and `Data` has `N/A` value. Cannot be decoded
![image](https://user-images.githubusercontent.com/15363559/232800474-f90d41d3-5974-452e-87de-0d31b76144ec.png)

### Describe the solution you'd like
Tooltip with explanation?

### Is it already possible to achieve the same outcome in any other way? If so, how?
Simplest solution applied so far (just `N/A`)

**Comment by michele-franchi** [comment]
This is solved.
