### ISSUE TITLE
Show decoded values for known contract events

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#142]
### Please describe the problem that your request should resolve.

Contract details arguments are encoded.

### Describe the solution you'd like
Show decoded values for known contract events, instead of encoded values. 

### Is it already possible to achieve the same outcome in any other way? If so, how?
No

### Additional context

<img width="1807" alt="image" src="https://user-images.githubusercontent.com/11598532/233102279-3e5f0e61-6fe5-4eaa-863e-f0922bcbdbcf.png">

**Comment by michele-franchi** [comment]
Hint to decode arguments:

args - a list of event constructor arguments as big integers. Contract bytecode doesn't contain metadata describing the types of the contract events. As a result, we can only report the binary blobs to the user, which can be either a integer (probably denoting an amount or counter), or public key. The integer can be converted to public key (256-bits) binary in Elixir (or Erlang) shell:

iex(aeternity@localhost)3> <<32049452134983951870486158652299990269658301415986031571975774292043131948665 :: 256>>
<<70, 219, 88, 217, 218, 57, 227, 219, 63, 200, 168, 207, 16, 238, 173, 185,
  185, 214, 3, 207, 227, 124, 221, 54, 36, 147, 13, 144, 171, 6, 142, 121>>

**Comment by michele-franchi** [comment]
In the current situation args are displayed with a copy chip but I don't see it to be very useful.
In some cases we can decode events but in other cases we cannot so we should come up with a better way to print args.

An example of args is:
32753730148209424528669618570854040268882117776994679953149143100586060638861,
78634212950425581798721990771303373185415516650444519182691076205419750101273,
4002733541013132843

Maybe an expandable button to show encoded events?

**Comment by michele-franchi** [comment]
@danilosierrac the problem here is that we should show something like:

[arg0] 32753730148209424528669618570854040268882117776994679953149143100586060638861
[arg1] 78634212950425581798721990771303373185415516650444519182691076205419750101273
[arg2] 4002733541013132843

but if we add it directly to the table it could be a mess but I would give it a try.

Something like the "Logs" column:
<img width="1328" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/626711c0-bddb-4df6-b46f-370c63e842bc">

Could you experiment with both? Data directly in our "Data" column and the alternative with the expandable button?

In any case the final structure of the Events table in the Smart Contract details page should be:

| Hash | Date | Name | Data |
|--------|--------|--------|--------|
| th_2p5srEC...9Q | Block height an date | Transfer | args here |

**Comment by danilosierrac** [comment]
I think we can export that oracle approach  a bit. Will give it a try.

**Comment by danilosierrac** [comment]
Something like this perhaps?

![Image](https://github.com/aeternity/aescan/assets/7396728/8952efd8-9597-4da4-ad45-201edc0f291b)

**Comment by lukeromanowicz** [comment]
Looks good to me 👍  @michele-franchi do you approve the proposed design?

**Comment by michele-franchi** [comment]
@lukeromanowicz I requested some changes and here's the updated one:
<img width="948" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/3e6c3c10-6647-4693-aacc-503d0a998e98">
