### ISSUE TITLE
NFT details inventory tab

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#146]
A new tab called "Inventory" should be visible in the NFT details page with the following paginated table:

| Token ID | Owner |
|--------|--------|
| 1 | ak_2QkttUg...Yd |

[Example NFT without templates](https://mainnet.aeternity.io/mdw/v2/aex141/ct_2w7MHbcyk5iM4yijZmjGcUF2DSZuVM1Mueppx5SSvPn5cgLJuZ/owners).

If the NFT has `mintable_templates` extension a different paginated table should be displayed with the following columns:

| Template ID | Supply | Limit | Create Transaction |
|--------|--------|--------|--------|
| 8 | 8 | 8 | th_ojhH9bD...z4 | 

[Example NFT with templates](https://testnet.aeternity.io/mdw/v2/aex141/ct_2oq4kSd4j1VkkbupueXLdHwYEJdY8Ntzvp1FFkMB1gYyXkYPcV).
[Example templates](https://testnet.aeternity.io/mdw/v2/aex141/ct_2oq4kSd4j1VkkbupueXLdHwYEJdY8Ntzvp1FFkMB1gYyXkYPcV/templates).

When a template is expanded the user should be able to see NFTs inside a template and the table should contain:
| Token ID | Owner | Create Transaction |
|--------|--------|--------|
| 36 | ak_8Ujt76Q...YN | th_NxjFwCY...ot | 

[Example tokens in a NFT template](https://testnet.aeternity.io/mdw/v2/aex141/ct_2oq4kSd4j1VkkbupueXLdHwYEJdY8Ntzvp1FFkMB1gYyXkYPcV/templates/8/tokens).

**Comment by janmichek** [comment]
![Image](https://github.com/aeternity/aescan/assets/15363559/36c397aa-6cca-4601-acb8-57e4f615e280)


Check by this link once deployed https://testnet.aeternity.io/mdw/v2/aex141/ct_2oq4kSd4j1VkkbupueXLdHwYEJdY8Ntzvp1FFkMB1gYyXkYPcV/templates?limit=10

**Comment by janmichek** [comment]
It's not gonna be easy to develop, as I cannot find combination of templates with owners ./
Do we have any example?
