### ISSUE TITLE
Total seen oracles is misleading

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/aescan#152]
### Please describe the problem that your request should resolve.
"Total seen" oracles information in general blockchain statistics panel looks a little bit misleading to me. It's using `inactive_oracles` field of the `/mdw/v2/totalstats` endpoint but what it really means is the number of expirations that happened. It means that a single account could become an oracle, expire and then become an oracle again multiple times while we count it as a unique oracle every time. 

### Describe the solution you'd like
I suggest changing the caption to reflect the meaning of the value of changing the value to some other source if it's available somewhere

**Comment by janmichek** [comment]
> Most likely will be fixed by [aeternity/ae_mdw#1274](https://github.com/aeternity/ae_mdw/pull/1274)

@lukeromanowicz  Could you help me to check, here?

**Comment by lukeromanowicz** [comment]
Still seems unresolved. I posted a followup in https://github.com/aeternity/ae_mdw/issues/1278
