### ISSUE TITLE
Implement counter in oracles page

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/aescan#159]
### Please describe the problem that your request should resolve.
Oracles page is missing pagination information due to invalid value of inactive_oracles in middleware's `GET /v2/totalstats` endpoint. Please implement it once it's fixed on mdw side. 

Ticket to track: https://github.com/aeternity/ae_mdw/pull/1274

**Comment by janmichek** [comment]
New tracking here https://github.com/aeternity/ae_mdw/issues/1278
