### ISSUE TITLE
Account label is displayed twice

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#197]
### Context information

application version: dev
device: 
browser: 
operating system: 

### Steps to reproduce
- Open [ak_QcxSaniCR8VZrQpDqYcNuKvZDMfUzG6QTwEZhzRGiQm8Bsjwi](https://aescan.dev.aepps.com/accounts/ak_QcxSaniCR8VZrQpDqYcNuKvZDMfUzG6QTwEZhzRGiQm8Bsjwi)

### What is expected?
- Account label is displayed once

### What is actually happening?
- Account label is displayed two times 

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/11598532/235742332-bf429d73-7647-48d5-a548-4e4a3ea99a5e.png">

**Comment by lukeromanowicz** [comment]
Closing as it's been already fixed 

![Image](https://github.com/aeternity/aescan/assets/46789227/16fadea2-168f-45e1-8ac0-539477a48a10)
