### ISSUE TITLE
Oracle query tuning

### ISSUE THREAD

**Issue by janmichek** [aeternity/aescan#200]
### Please describe the problem that your request should resolve.
Some values needs to be adjusted because was not delivered by MDW

### Describe the solution you'd like
Once the MDW response will be updated, we can accommodate it on our side
Tracking: https://github.com/aeternity/ae_mdw/issues/1295

- [ ] Replace `N/A` values with values from response
- [ ] Enable 4 versions of query panel (Response available, Query timed out, Response expired, ...)

### Is it already possible to achieve the same outcome in any other way? If so, how?
Not possible

### Additional context
Current status
![image](https://user-images.githubusercontent.com/15363559/236007821-6a18fee4-65f4-4cb3-89a8-8553c19935de.png)

**Comment by michele-franchi** [comment]
This can now be implemented with `Queried At` and `Respond At` columns.
The endpoint https://mainnet.aeternity.io/mdw/v2/oracles/oracleId/queries should be used.

**Comment by michele-franchi** [comment]
Already implemented.
