### ISSUE TITLE
Hash symbol inconsistency

### ISSUE THREAD

**Issue by janmichek** [aeternity/aescan#224]
### Context information

Sems like there is an unfinished idea after inheriting previous design.

So we have this `hash symbol`
![image](https://github.com/aeternity/aescan/assets/15363559/5432be9d-c17f-4c2a-83ef-58704bf53a25)
It's present in desktop view but not present in mobile view. Which I think it's first bug

Secondly, I think the original idea behind this was somehow to help users with visual orientation. 
Eg: Transactions hashes will have this red `th` prepended, contracts will have green `ct` prepended, ... somehow color code different hashes

So we should finish the idea or drop it. Leaving this for consideration @danilosierrac 

### Steps to reproduce
all over app

### What is expected?
consistent usage of that idea

### What is actually happening?
inconsistent usage

**Comment by janmichek** [comment]
After discussion we would like to remove it

**Comment by danilosierrac** [comment]
I am ok with removing it! Generally speaking that was meant to be a marker for each row. @michele-franchi what do you think?

**Comment by danilosierrac** [comment]
I removed them (hid) from the designs as well. Let me know if this ticket needs to be open still @janmichek @michele-franchi

**Comment by janmichek** [comment]
Thank you, we will keep this open for implementation
