### ISSUE TITLE
ChannelSnapshotSolo wierd values

### ISSUE THREAD

**Issue by janmichek** [aeternity/aescan#227]
### Context information
in code

### Steps to reproduce

Go to /transactions?txType=channel_snapshot_solo
![image](https://github.com/aeternity/aescan/assets/15363559/57395744-006d-49ab-b58d-e0de5a65b003)

### What is expected?
More reliable values to show

### What is actually happening?
There is the same value printed. Is it correct? If so the link should be enabled

![image](https://github.com/aeternity/aescan/assets/15363559/c96616a9-a76b-4de3-bcd6-e3256c0bde7f)

**Comment by michele-franchi** [comment]
The second argument should be the channel id, instead of the same account value.


![Image](https://github.com/aeternity/aescan/assets/11598532/60643b5a-f971-4029-abec-9c1fbe4de8b2)
