### ISSUE TITLE
Only up to four transactions can be displayed on the dashboard

### ISSUE THREAD

**Issue by CharisSiarampalis** [aeternity/aescan#245]
### Context information

application version: pr-244
device: Samsung Galaxy S22
browser: Every Browser
operating system: Android
### Steps to reproduce
1.Open https://pr-244-aescan.stg.aepps.com/ and go to the dashboard
2.Scroll down the page and go to microblocks
3.Find one microblock that has more than four transactions
4.Click on it
### What is expected?
All transactions are able to be seen
### What is actually happening?
It only displays four transactions. Even the text above them says that there are only four transactions in this microblock.
![microblocks](https://github.com/aeternity/aescan/assets/42606212/844b76ca-a534-4ff2-b521-9fafd306dc11)

**Comment by janmichek** [comment]
It is an issue on desktop as well

**Comment by lukeromanowicz** [comment]
@michele-franchi @danilosierrac we will need a design for "loading more" content of swiper on mobile devices
