### ISSUE TITLE
When using a mobile device menu stays open when navigating to another page of the app

### ISSUE THREAD

**Issue by csiarab** [aeternity/aescan#246]
### Context information

application version: pr-244
device: Samsung Galaxy s22
browser: Firefox, Chrome
operating system: Andoid

### Steps to reproduce
1.Go to https://pr-244-aescan.stg.aepps.com/
2.Click on the menu to open it
3.Scroll down the page without closing it
4.Clik on another link like terms of service

### What is expected?
When navigating to another page menu should be closed by default. 
### What is actually happening?
Right now the menu stays open requiring the user to close it manually cy clicking on the menu button again.

https://github.com/aeternity/aescan/assets/42606212/daf7b634-6e88-40f1-b12a-1ef3da0d3931

**Comment by janmichek** [comment]
fixed here https://github.com/aeternity/aescan/pull/244
