### ISSUE TITLE
 When using a mobile device when selecting a microblock with one transaction it looks like it has three instead.

### ISSUE THREAD

**Issue by CharisSiarampalis** [aeternity/aescan#248]
### Context information

application version: pr-244
device: Samsung Galaxy s22
browser: All browsers
operating system: Android

### Steps to reproduce
1.Go to the dashboard
2.Scroll down to the microblocks
3.Select on microblock with 4 transactions, then 3, 2 and finally one
4.Observe the amount of transactions that can be scrolled bellow them
### What is expected?
The amount of the transactions appearing bellow should much the number written on the box
### What is actually happening?
When selecting o vox with three transactions or more only three dots can be seen. 
Then when we select a box with two the dots and scrollable transactions decrease to two.
But then when we select a box with one three dots appears again. The same transaction is repeated three times.

https://github.com/aeternity/aescan/assets/42606212/38afdfcb-e8d6-4ee4-bace-11788d93694e

**Comment by janmichek** [comment]
The issue is present on desktop as well

**Comment by CharisSiarampalis** [comment]
@lukeromanowicz I tried to reproduce on the production but it seems it was fixed andno longer reprodusable.
On the production the microblock transactinos look ok.

But on the dev environment i noticed something different. At first everything looks correct but when a new microblock appears the dots under the microblock transactions dissapear


https://github.com/aeternity/aescan/assets/42606212/9df3ed7b-f7e2-46e1-863f-8963579e3d36

Should i just create another bug?

**Comment by lukeromanowicz** [comment]
@CharisSiarampalis thank you for reuploading the video. I'll try to handle all the reported issues with one PR. Thanks!

**Comment by lukeromanowicz** [comment]
@CharisSiarampalis please check if this issue still exists in the current version on the develop environment. Since we went back to the previous version, this issue might not be relevant anymore.

**Comment by lukeromanowicz** [comment]
@CharisSiarampalis gentle reminder about this :)

**Comment by CharisSiarampalis** [comment]
@lukeromanowicz I checked dev for this and i noticed that when the microblock has 2,3 or 4 transactions everything looks correct. 
But on a microblock with 5 or more the user can only see four transactions while going through them. 
Also when the microblock has 1 transaction three dots appear like the block has three. And when the user goes through the same one appears.

https://github.com/aeternity/aescan/assets/42606212/15e15fb9-7685-478d-ad98-0b14d592f01b

**Comment by lukeromanowicz** [comment]
This behavior is not a regression. That has always been the case. @michele-franchi @janmichek @danilosierrac  please advise what do we want about this :point_up:

**Comment by janmichek** [comment]
> This behavior is not a regression. That has always been the case. @michele-franchi @janmichek @danilosierrac please advise what do we want about this ☝️

The part with Swiper dots truly is a bug. The other parts are disputable.
There may be problems to pass more than 4 slides to Swiper, but we never tried, so we can experiment with this.

**Comment by danilosierrac** [comment]
I would disspear the dots if its only one item in it. Is that doable? Maybe "display:none" it?

**Comment by lukeromanowicz** [comment]
WDYT about limiting the transactions displayed in the dashboard's microblock section to 4 both on desktop and mobile? There is a "show all" button in case somebody wants to see more. I think that would simplify things significantly

@danilosierrac @janmichek @michele-franchi
