### ISSUE TITLE
Going through the list of the names connected to an account is not working correctly

### ISSUE THREAD

**Issue by CharisSiarampalis** [aeternity/aescan#271]
### Context information

application version:  0.2.1
device: Laptop
browser: Chrome
operating system: Windows

### Steps to reproduce
1.Go to https://www.aescan.io/
2.Go to an account with many names
3.Click on the AENS Names tab
4.Click next and back a few times

### What is expected?
User should be able to cycle through the whole list of the account's names.
### What is actually happening?
Clicking on the next button does not work. Only after clicking next and back a few times the page changes. and it appears to show the last first

https://github.com/aeternity/aescan/assets/42606212/c6967edf-e326-4d32-8041-27f0b2011cfa

![image](https://github.com/aeternity/aescan/assets/42606212/676c5eef-74ad-4bc6-a243-1e736b2070d8)

**Comment by janmichek** [comment]
@csiarab Thanks for reporting. Could you also attach the link to that particular account that has many names? That would help us to debug faster

**Comment by csiarab** [comment]
@janmichek Its one of my test accounts : ak_6Qc7vF86Z1jxxiFXcK2oaZtKw2FSDtHHduVDXGPxeQ73ovsF5

**Comment by janmichek** [comment]
I found out its a MDW bug. Created the issue there. Tracking https://github.com/aeternity/ae_mdw/issues/1473

**Comment by michele-franchi** [comment]
This one should have been fixed, to be checked.

**Comment by janmichek** [comment]
Yep, just checked this. Working as expected. Closing it
