### ISSUE TITLE
Entry Point chip is empty

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#276]
### Context information

application version: 
device: 
browser: 
operating system: 

### Steps to reproduce
- Open https://testnet.aescan.io/contracts/ct_B2Rp1ZmvS2tcQu7GpSRt3tcY7E8aou56LYQLiao1RHCZr5piK

### What is expected?
Something else should be displayed instead of an empty chip.

### What is actually happening?

<img width="1218" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/dc784655-c872-4eab-8048-dfaaa9eb88ab">

**Comment by thepiwo** [comment]
it's happening as that contract has been created using contract factories "Contract.create" in sophia, we could probably be able to figure that out and show it somewhat nicely using https://github.com/aeternity/ae_mdw#v2contractscalls, but this could also be a separate feature, showing all contract calls nicely in general

**Comment by lukeromanowicz** [comment]
Looks like the following two endpoints do not always overlap: 

[https://testnet.aeternity.io/mdw/v2/txs\?direction\=backward\&limit\=10\&type\=contract_call\&contract\=ct_B2Rp1ZmvS2tcQu7GpSRt3tcY7E8aou56LYQLiao1RHCZr5piK](https://testnet.aeternity.io/mdw/v2/txs?direction=backward&limit=10&type=contract_call&contract=ct_B2Rp1ZmvS2tcQu7GpSRt3tcY7E8aou56LYQLiao1RHCZr5piK)

and

https://testnet.aeternity.io/mdw/v2/contracts/calls?contract_id=ct_B2Rp1ZmvS2tcQu7GpSRt3tcY7E8aou56LYQLiao1RHCZr5piK&limit=1

I would handle this issue by showing N/A - just like in other cases and create a separate feature request for a better presentation of the contract calls overall.
