### ISSUE TITLE
ChannelCloseSoloTx transcations are not being displayed on the account detail page

### ISSUE THREAD

**Issue by CharisSiarampalis** [aeternity/aescan#294]
### Context information

application version: v0.2.1
device: All
browser: Every browser
operating system: All

### Steps to reproduce
1. Go to develop
2. Search for the account ak_ozzwBYeatmuN818LjDDDwRSiBSvrqt4WU7WvbGsZGVre72LTS
3. Select ChannelCloseSoloTx  from the list

### What is expected?
User should be abler to see the ChannelCloseSoloTx  transactions. This account has one as can be seen on the state channels page.
### What is actually happening?
A message There is no data available is displayed

Account detail page:
![image](https://github.com/aeternity/aescan/assets/42606212/e23a5f3c-5ef3-417e-a202-9220a0ae6e16)

Transaction on the state channels page:
![image](https://github.com/aeternity/aescan/assets/42606212/6ff5392d-6942-49b5-affe-72e781f69ade)

**Comment by lukeromanowicz** [comment]
@CharisSiarampalis the ak_ozzw... account you mentioned is the initiator but ChannelCloseSoloTx transactions has been dispatched by the Responder, as per history available in: https://aescan.dev.aepps.com/state-channels/ch_22usvXSjYaDPdhecyhub7tZnYpHeCEZdscEEyhb2M4rHb58RyD

When you go to the Responder's account, the ChannelCloseSoloTx is displayed correctly.

![Image](https://github.com/aeternity/aescan/assets/46789227/accd1c2e-9e39-47ea-9def-26b544f58c21)

I think everything is working as expected, please confirm that's the case

**Comment by lukeromanowicz** [comment]
@CharisSiarampalis ping 😃

**Comment by CharisSiarampalis** [comment]
@lukeromanowicz If only the responder can see this transaction then it is working as expected.
I just thought that since the other account is part of this transaction, it should show up.

**Comment by lukeromanowicz** [comment]
@CharisSiarampalis what you are saying is correct when there are multiple accounts participating in *transaction*. In this specific case, there are multiple accounts participating in the state channel but the transaction you mentioned is dispatched only by one of the accounts and sent against the state channel. The second account did not participate in that transaction at all so the transaction is not showing up there. I hope this clarifies things, but thanks for the report. It looked at first glance as an error to me too.
