### ISSUE TITLE
Microblock details

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#303]
A new panel should be added with the following:
- Microblock Hash
- Height
- Time
- Transactions count

Something should also tell the user a microblock is inside a keyblock and there's a sequence. Ideally a simple navigation between them would be great.

**Comment by danilosierrac** [comment]
I assume this is in its own page right @lukeromanowicz ? Or do you want this and the keyblock details as additional panels into the dashboard?

**Comment by danilosierrac** [comment]
How does the microblock hash start with? mh_... ?

**Comment by lukeromanowicz** [comment]
@danilosierrac right and right :heavy_check_mark: Microblocks should have their own details page and the hash starts with mh_...
