### ISSUE TITLE
All Hints revision

### ISSUE THREAD

**Issue by janmichek** [aeternity/aescan#307]
### Please describe the problem that your request should resolve.
Once we have all Hint-related issues merged, would be good to take a final look again.

### Describe the solution you'd like
- [ ] #411
- [ ] add references to the protocol. For example a link [Learn more](https://github.com/aeternity/protocol/blob/7172e2c2bfcb13d8d77276ec6025cb8fffa2b4a7/channels/ON-CHAIN.md#channel_snapshot_solo), with transactions that can be linked from the protocol repo.
- [x] Go through all the hints. We may find some misalignments, because we were creating it on the go gradually. Both in implementation and content
- [x] replace `Estimated date, time, and block height` with `Block height and estimated date and time`
- [x] doublecheck casing of Entities ?
- [x] Recieve final feedback from Marco and Philipp for all hints.
- [x] hint icon can still be few pixels above
- [x] wording Was vs Has been
- [x] links in toolips are unreachable, it closes when losing focus (regression)
- [x] check if the labels in listing match the ones in details of corresponding entity

**Comment by janmichek** [comment]
## Dashboard
![image](https://github.com/aeternity/aescan/assets/8124114/2f5714dd-19a8-41e3-8e87-b4ffa6402168)
![image](https://github.com/aeternity/aescan/assets/8124114/90c91c0e-5def-4dfd-9bf7-7458cdba17ee)

- [ ] I cannot click on the links here, the hint always disappers
- [ ] request: personally, I would also love to be able to click on the account that receives the BRI somewhere (not sure where the link should be added, but it would be nice to have in terms of transparency). I think it makes sense to add it into the hint of the second image

![image](https://github.com/aeternity/aescan/assets/8124114/1949e1fc-3a82-4f6d-9767-0cd59c31ecec)
- [ ] request: add a link to the account that holds the burned tokens

**Comment by janmichek** [comment]
> consider hint icon before the label

This would partly resolve the issue of too many icons for the mobile view. At least wouldn't be such a visual mess. I think that's why the reference explorers are using it

**Comment by janmichek** [comment]
Ad

> consider hint icon before the label

What do you think about this idea? I personally like it. I posted the preview in our internal chat.
I think there is a good reason for it in referential explorers.
It also solves the issue of too much visual mess in the mobile version.
@lukeromanowicz @michele-franchi @danilosierrac 

Let me know your thoughts.

**Comment by lukeromanowicz** [comment]
I love this idea. If you are interested in such a hint, you know exactly where to find it. If you are not - it's easier to ignore it.

**Comment by janmichek** [comment]
@marc0olo What do you think about this idea?

> add references to the protocol. For example a link [Learn more](https://github.com/aeternity/protocol/blob/7172e2c2bfcb13d8d77276ec6025cb8fffa2b4a7/channels/ON-CHAIN.md#channel_snapshot_solo), with transactions that can be linked from the protocol repo.

**Comment by janmichek** [comment]
As there was no discussion, I separated the issue https://github.com/aeternity/aescan/issues/411
