### ISSUE TITLE
Hints content revision for next release

### ISSUE THREAD

**Issue by janmichek** [aeternity/aescan#326]
Please go through the pages:

- [x] dashboard
- [x] state channel details
- [x] state channel
- [x] transactions
- [x] token details
- [x] tokens
- [x] oracle details
- [x] oracles
- [x] account details
- [x] name details
- [x] names
- [x] smart contracts

and evaluate the content.

Ideally, provide comments to this Issue.

**Comment by marc0olo** [comment]
@janmichek are the hints already visible on the latest dev deployment or do I have to check several PRs? if so a short summary of where to check what would be great 🙏

**Comment by marc0olo** [comment]
## state channel details

![image](https://github.com/aeternity/aescan/assets/8124114/a2f59780-237d-4c66-a3d4-f4393f95abb0)
- [ ] replace: "While the status is "Open", the State Channel participants can execute an unlimited amount of transactions off-chain with instant finality. The status will be "Closed" if one of the participants executes either a `ChannelCloseMutualTx` or a `ChannelSettleTx`.

![image](https://github.com/aeternity/aescan/assets/8124114/25306ecd-3684-44ac-9839-054bfb99d3bb)
- [ ] replace with: "The total amount of AE coins that have initially been deposited to the State Channel by initiator and responder combined."

![image](https://github.com/aeternity/aescan/assets/8124114/bb90b4ba-2cd5-429d-a772-80ace2db6f55)
- [ ] replace with: "The account that initiated the creation of the State Channel and covered the fees for its creation."

![image](https://github.com/aeternity/aescan/assets/8124114/b2deb728-8b0f-4a44-a31f-d04afe29d222)
- [ ] change label to "On-Chain TXs" or "On-Chain Transactions" (keep spelling consistent with dashboard 😅 )
- [ ] replace with: "Amount of on-chain transactions related to the State Channel. Participants can for example deposit to, withdraw from or provide a snapshot of the State Channel to the chain."

**Comment by marc0olo** [comment]
##  state channel

- [ ] refer to **dashboard** and **state channel details** comments

**Comment by marc0olo** [comment]
## transactions (WIP)

![image](https://github.com/aeternity/aescan/assets/8124114/120ad327-6545-4971-8b75-f8be3bee9e98)
- [ ] replace with: "Keyblock height and exact date and time when the transaction has been executed by inclusion into a microblock."

**Comment by hanssv** [comment]
Spot on @marc0olo 👍

**Comment by marc0olo** [comment]
## token details

![image](https://github.com/aeternity/aescan/assets/8124114/86e3ed0a-4df2-472b-9c00-dcf95c86f110)
- [ ] replace with: "Price of the token in AE and USD."

![image](https://github.com/aeternity/aescan/assets/8124114/d5eebb26-3cde-47a1-b6b6-fde22cd63ce9)
- [ ] replace with: "Amount of tokens in circulation."
    - reason: my assumption is that burned tokens won't be included in that value, so that statement was not accurate

![image](https://github.com/aeternity/aescan/assets/8124114/114cd544-9432-4e46-9a36-32f81f1905b5)
- [ ] replace "interface" with "fungible token standard"
    - we are displaying the hints mainly for the average joe, right? 😁 

![image](https://github.com/aeternity/aescan/assets/8124114/e4bb49c8-7977-479c-ab02-0a1c67704bb2)
- [ ] replace with: "Extensions that are implemented for this token according to the creator of the Smart Contract."

**Comment by marc0olo** [comment]
## oracle details

![image](https://github.com/aeternity/aescan/assets/8124114/6b2cb5b1-1061-4eeb-8931-2d28ebcf235b)
- [ ] "Block" -> "Keyblock"
- [ ] "estimated date" -> "exact date"

![image](https://github.com/aeternity/aescan/assets/8124114/30326dc2-3bdb-4ea6-9cee-ebf3fbe4d03a)
- [ ] "Block" -> "Keyblock"
- [ ] "estimated date" -> "exact date"

![image](https://github.com/aeternity/aescan/assets/8124114/5113bcd4-a6c3-4326-bd40-80754f56bd2d)
- [ ] rename label to "Last queried" ?
- [ ] replace hint with: "Keyblock height and exact date of the last query to the Oracle."

![image](https://github.com/aeternity/aescan/assets/8124114/1d2a32ed-9f8b-4652-8879-2e7a1b042326)
- [ ] replace with: "The default lifetime of an Oracle is 500 keyblocks. The initial lifetime can be set to a higher value and an Oracle can be extended anytime, e.g. by setting up an automated service. In case the Oracle lifetime is passed, the Oracle operator can re-register it anytime."

![image](https://github.com/aeternity/aescan/assets/8124114/1b76aef9-e9cf-40d9-af9c-a41fca6977a0)
- [ ] replace with: "The default fee required to query an Oracle is 30,000 aettos and is defined by the Oracle operator when registering it. The Oracle operator can set it to any value and even allow to query the Oracle for free."

![image](https://github.com/aeternity/aescan/assets/8124114/0cb5d060-cd2c-44cc-84dc-18aa9bfd30a0)
- [ ] rename label to "Operator"
- [ ] replace hint with: "The account that operates the Oracle."

![image](https://github.com/aeternity/aescan/assets/8124114/d12c0f9e-7c64-4dba-8bcf-6a16523fa646)
- [ ] replace with: "The default fee required to query an Oracle is 30,000 aettos and is defined by the Oracle operator when registering it. The Oracle operator can set it to any value and even allow to query the Oracle for free."

![image](https://github.com/aeternity/aescan/assets/8124114/525383a7-bb92-42ef-9735-504627ba7ff0)
- [ ] replace with: "Defines how long the response will be accessible in keyblocks. The displayed lifetime is relative and if a Smart Contract relies on the response, the user or a service should make sure the response is consumed during its lifetime."

![image](https://github.com/aeternity/aescan/assets/8124114/232a2ff9-9262-4371-89c4-76115d525581)
- [ ] replace with "The response payload to the given query."
    - not sure about the binary format 🤔 e.g. in this example here I see the account address: https://aescan.dev.aepps.com/oracles/ok_4HGhEdjeRtpsWzfSEJZnBKNmjgHALAifcBUey8EvRAdDfRsqc

**Comment by marc0olo** [comment]
## oracles

![image](https://github.com/aeternity/aescan/assets/8124114/2221db1f-b681-4183-9587-2259fa43a8d1)
- [ ] replace "creator" with "operator"

![image](https://github.com/aeternity/aescan/assets/8124114/1f12ee08-b049-4f5c-a1ed-54f6844d80ba)
- [ ] "Block" -> "Keyblock"
- [ ] "extimated" -> "exact"

![image](https://github.com/aeternity/aescan/assets/8124114/9bf0e1b6-767b-4d8d-96fd-241688920f52)
- [ ] replace with: "The default lifetime of an Oracle is 500 keyblocks. The initial lifetime can be set to a higher value and an Oracle can be extended anytime, e.g. by setting up an automated service. In case the Oracle lifetime is passed, the Oracle operator can re-register it anytime."

![image](https://github.com/aeternity/aescan/assets/8124114/ffdfe855-d237-402f-b9ce-433ec2c18cda)
- [ ] replace with: "The default fee required to query an Oracle is 30,000 aettos and is defined by the Oracle operator when registering it. The Oracle operator can set it to any value and even allow to query the Oracle for free."

**Comment by marc0olo** [comment]
## account details

![image](https://github.com/aeternity/aescan/assets/8124114/582f607b-6d19-43f9-9df4-33eee67a5780)
- [ ] "Fiat" -> "USD" (depending on consistency with other places where I commented)

![image](https://github.com/aeternity/aescan/assets/8124114/b4531169-cc6c-4c45-85df-c7188bce79b9)
- Is this true? Or is the the amount of transactions executed by this account? 🤔 @michele-franchi
  - edit: I think it is correct, looking at the tx-table

![image](https://github.com/aeternity/aescan/assets/8124114/d6bb97b1-40fe-4fde-9be1-3a5f2ec34387)
- [ ] "Names" -> "names" (depends on consistency, see other comments)

![image](https://github.com/aeternity/aescan/assets/8124114/c195415a-dcb8-46c4-b97f-e8d1c67d09ef)
- [ ] replace with: "The nonce that has been used to execute the last transaction for the account. The nonce is used to prevent replay attacks and to keep transactions in the right order. If a transaction with a way higher nonce is broadcasted, it won't be executed until all transactions with lower nonces are executed."

![image](https://github.com/aeternity/aescan/assets/8124114/dd628718-dae5-4e4f-a036-75848773abb5)
- [ ] replace with: "Keyblock height and exact date and time when the transaction has been executed by inclusion into a microblock."

![image](https://github.com/aeternity/aescan/assets/8124114/e33ec4a1-3b79-49f5-b3b2-45659e76aa85)
- [ ] Add a hint for "Data" label: "The data displayed differs for each tx type."
- [ ] hints for tx-type within the column values are missing (should be similar to those on "transactions")

**Comment by marc0olo** [comment]
## name details

![image](https://github.com/aeternity/aescan/assets/8124114/9653bf51-cc13-4bac-85ac-1b931e558b76)
- [ ] "Name" -> "name" ? (consistency topic)

Note: for expired names we should change the label to "Last owner" and also adjust the hint maybe? cc @michele-franchi 

![image](https://github.com/aeternity/aescan/assets/8124114/da53dd41-a4a2-45c0-8d44-001baad56f39)
- [ ] "Block" -> "Keyblock"
- [ ] "estimated" -> "exact"
- [ ] "Name" -> "name" ? (consistency topic)

### Expires
![image](https://github.com/aeternity/aescan/assets/8124114/60c9845e-1cf9-47ab-b616-3064a7a24295)
- [ ] "Block" -> "Keyblock"
- [ ] Add sentence: "After expiration, the name enters into a revoked state and can be claimed again after a fixed timeout of 2016 keyblocks."

### Expired
![image](https://github.com/aeternity/aescan/assets/8124114/dfe34523-f03f-429c-aebb-abf11fa74784)
- [ ] "Block" -> "Keyblock"
- [ ] "estimated" -> "exact"
- [ ] Add sentence: "After expiration, the name entered into a revoked state and can be claimed again after a fixed timeout of 2016 keyblocks."

### In Auction
![image](https://github.com/aeternity/aescan/assets/8124114/abed90b3-94db-43e8-98c2-70b08a835029)
- replace with: "Keyblock height and estimated date and time when the auction ends and the name will be activated and owned by the highest bidder."

Note: maybe change label to "Ends" instead of "Expires" ? I remember we wanted to keep it simple, but the hint needs to have a different content anyway 🤷‍♂️ cc @michele-franchi 

![image](https://github.com/aeternity/aescan/assets/8124114/397ead96-5e1c-419c-8a41-e0d631614d86)
- [ ] "Name" -> "name" ? (consistency topic)

![image](https://github.com/aeternity/aescan/assets/8124114/4eb4c487-ae4f-4d3f-9819-e0e17ffcb2b6)
- [ ] "Name" -> "name" ? (consistency topic)

![image](https://github.com/aeternity/aescan/assets/8124114/34fbafc2-f9ec-49c3-ad65-3f5e6edb66c9)
- [ ] "Block" -> "Keyblock"
- [ ] "estimated" -> "exact"

**Comment by marc0olo** [comment]
## names

### Active
![image](https://github.com/aeternity/aescan/assets/8124114/ea1dceb1-0cee-4495-99eb-a679fee4e8d8)
- [ ] replace with: "Account that paid the shown price to claim the name."

![image](https://github.com/aeternity/aescan/assets/8124114/394d7dd4-4f57-44b7-bc42-ad2ca512673f)
- [ ] "Name" -> "name" ? (consistency topic)

![image](https://github.com/aeternity/aescan/assets/8124114/53a489f5-a814-4fcd-882e-d1f04152aaab)
- [ ] replace with: "The account the name points to."

### In Auction
![image](https://github.com/aeternity/aescan/assets/8124114/3daf55ac-36a5-4dfb-80e1-fbbe287b32b3)
- [ ] "need to be auctioned" -> "are always auctioned"

![image](https://github.com/aeternity/aescan/assets/8124114/4c82a15d-d204-406e-9fc0-16b4947ba677)
- [ ] "Block" -> "Keyblock"

![image](https://github.com/aeternity/aescan/assets/8124114/b90c2664-24b0-43bc-9184-1b22f3c3035a)
- here we should add an info about the required min. bid increase which I wasn't able to figure out quickly (cc @michele-franchi)

### Expired
![image](https://github.com/aeternity/aescan/assets/8124114/741edcd3-8e8d-44fa-8465-8dbe03d47ccb)
- [ ] "Block" -> "Keyblock"
- [ ] "estimated" -> "exact"
- [ ] "Name" -> "name" ? (consistency topic)
- [ ] "address" -> "account"

![image](https://github.com/aeternity/aescan/assets/8124114/b4d749c8-eeaf-4c18-a3d6-4d5ce53575eb)
- [ ] replace with: "Account that previously paid the shown price to claim the name."

![image](https://github.com/aeternity/aescan/assets/8124114/841d649f-9889-40b4-a57e-007ed993e471)
- [ ] "Name" -> "name" ? (consistency topic)

**Comment by janmichek** [comment]
> 



> 

I agree to use Keyblock instead of Block.

After the observation of 2 of our competitors, they are sung Big Caps in labels but small caps in hints. Both the same approach, so I guess we can imitate it.

![image](https://github.com/aeternity/aescan/assets/15363559/335bc26d-026c-47b0-9971-51ab81a32eab)

Agree?

**Comment by marc0olo** [comment]
> After the observation of 2 of our competitors, they are sung Big Caps in labels but small caps in hints. Both the same approach, so I guess we can imitate it.

this is exactly how I would propose it, too. great to hear that they are using the same approach. makes it a lot easier to avoid spelling inconsistency

**Comment by michele-franchi** [comment]
Agree, let's use lowercase then 👍

**Comment by marc0olo** [comment]
I have another topic (if not already mentioned above)

![image](https://github.com/aeternity/aescan/assets/8124114/5fa24015-c525-4efb-8f68-498d24a5fd23)
- [ ] change label to "Response format"

**Comment by janmichek** [comment]
In state channels there is actually estimated time calculated on FE from keyblock
![image](https://github.com/aeternity/aescan/assets/15363559/6a03a2e7-97ab-4868-ad26-fad465bc8713)

**Comment by marc0olo** [comment]
> In state channels there is actually estimated time calculated on FE from keyblock

ok, but why? 🤔 but I am also seeing some inconsistency here again for "Last Updated" (just in case you want to align that also everywhere)

**Comment by janmichek** [comment]
> > In state channels there is actually estimated time calculated on FE from keyblock
> 
> ok, but why? 🤔 but I am also seeing some inconsistency here again for "Last Updated" (just in case you want to align that also everywhere)

Simply just there is no `micro_time` in the response

**Comment by janmichek** [comment]
Where we are using `micro_time` I used the `exact` phrasing. Other places were left with `estimated`. I have added comment above per occurrence where it's not possible to use `exact`

**Comment by janmichek** [comment]
@marc0olo Some of the dashboard comments were more related to future improvements, so I move them here https://github.com/aeternity/aescan/issues/307 for clarity

**Comment by marc0olo** [comment]
yeah definitely enhancements / requests. makes sense 👍

**Comment by michele-franchi** [comment]
> Is this true? Or is the the amount of transactions executed by this account?

Yes, it's correct.

> maybe change label to "Ends" instead of "Expires" ? I remember we wanted to keep it simple, but the hint needs to have a different content anyway

Agree, it's "Ends" in the names table for "In Auction" names so it should be the same.

> for expired names we should change the label to "Last owner" and also adjust the hint maybe

Agree, it's "Last Owner" in the names table for "Expired" names.

**Comment by janmichek** [comment]
How about this 
>  here we should add an info about the required min. bid increase which I wasn't able to figure out quickly (cc @michele-franchi)

**Comment by michele-franchi** [comment]
That would also be great, please have a look at it.

**Comment by janmichek** [comment]
> That would also be great, please have a look at it.

Well I haven't found any information about it
https://docs.aeternity.com/protocol/AENS/

**Comment by janmichek** [comment]
> > That would also be great, please have a look at it.
> 
> Well I haven't found any information about it https://docs.aeternity.com/protocol/AENS/

Added
