### ISSUE TITLE
oracle details: creator / operator is not displayed

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aescan#332]
### Context information

application version: latest dev deployment
device: 
browser: 
operating system: 

### Steps to reproduce
visit: https://aescan.dev.aepps.com/oracles/ok_N7nzuDXwFHJtWKvVnV4AQtzZmUFSFvXFf79GsNdrA7XMEYxqi

### What is expected?
I would expect the creator / operator to be displayed

### What is actually happening?

currently "N/A" is shown

![image](https://github.com/aeternity/aescan/assets/8124114/b81ede78-e970-47af-87fa-023a802e1ed8)

**Comment by michele-franchi** [comment]
A solution for this would be to replace oracle hash prefix with `ak_`.
