### ISSUE TITLE
Show descriptions in entities pages

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#334]
Pages should have descriptions to explain what Transactions, Names, Smart Contracts, Tokens, Oracles and State Channels are.
Hint icons should be visible also in detail pages.

**Comment by janmichek** [comment]
Personally I am not a fan of this idea. Other similar explorers does not have it. I would say that hints are just right. If you wanna explore as a newcomer you can. But will be unnecessary content for advanced users, always visible at the top.

**Comment by janmichek** [comment]
I remember we have been discussing this with @marc0olo . Maybe you could also provide your thoughts here

**Comment by danilosierrac** [comment]
I am between a wall and a hard place because is agree with hints considering the amount of space it takes. But I also know Yani did more or less a hard ask to make this happen.
