### ISSUE TITLE
Input gets zoomed upon initialization of the page

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#338]
### Context information

application version: 
device:  Iphone 12
browser: Chrome
operating system: 

### Steps to reproduce

https://github.com/aeternity/aescan/assets/11598532/fbd858f2-d6b7-4f58-b70b-6b91f98c3c03

**Comment by michele-franchi** [comment]
This also happens when you click on any input / dropdown.

Hint: the problem with iOS is the font size

**Comment by Liubov-crypto** [comment]
Still reproducible for me on iPhone 13 in Safari browser ver. 17.1.2
