### ISSUE TITLE
Display decoded auth_data in GA Meta TX

### ISSUE THREAD

**Issue by rumyanar** [aeternity/aescan#341]
### Please describe the problem that your request should resolve.
When making a GA Meta transaction the parameters sent to the `authorize` function are recored under `auth_data` in the transaction. 
It's available in the Node and Middleware API, but it is not displayed in aeScan.

### Describe the solution you'd like
Display decoded `tx.auth_data` in the transaction details.
Edit: We can use `aecalldata.ContractByteArrayEncoder` to decode the data. it contains an array of all arguments passed to the authorize function.

### Is it already possible to achieve the same outcome in any other way? If so, how?
One can view the `auth_data` string in the Node API, and manually decode it using `aesophia_cli`

### Additional context
The data passed to the `authorize` function is different depending on the Generalized Account contract. 
For some contracts it might be meaningful to be displayed, while for others it might be useless.
For example in a Multisign transaction from Superhero the data is just a nonce number:
https://testnet.aescan.io/transactions/th_nBhTz4nFw7UHfb8UcuQUhWPebUpPgG5C7x8AgJiUZWasxgwJ9

For other contracts it may contain additional data about the transaction authorization, such as signature details:
https://testnet.aescan.io/transactions/th_2hDy1xk7edKwQgWMS6qwHYwVWXZroQNEaif9vFnjLUeME6KawN

**Comment by marc0olo** [comment]
I don't think we have a proper way to decode it right now without knowing the arguments of the auth function (cc @davidyuk @dincho @radrow @hanssv)

maybe it can be done with http compiler (but actually the plan is to get rid of it, right?! 😅)

**Comment by rumyanar** [comment]
It's contract bytecode, it should be encoded in the same way, regardless of what it contains. It can be decoded with the calldata library:

```
const decoder = new aecalldata.ContractByteArrayEncoder();
const result = decoder.decode(data);
```

In all cases it contains an array of the arguments passed to the `authorize` function.
The arguments may be different data types, which is a bit challenging to display, but I guess JSON.stringify() should be enough.
In the above example we have int, string and bytes array.

**Comment by rumyanar** [comment]
I now realized that the call_data in contract calls is decoded by the Middleware, and not by aeScan, so I created a related feature request there.

**Comment by davidyuk** [comment]
This only problem using [ContractByteArrayEncoder:decode](https://github.com/aeternity/aepp-calldata-js/blob/82b5a98f9b308482627da8d7484d213e9cf87151/src/api/ContractByteArrayEncoder.js#L12-L15) is that it won't recover record keys (ex `{ from: 'ak_...', to: 'ok_...'}` would be just `['ak_...', 'ok_...']`) and variant names. I don't think that middleware can handle it better, so I would use `aepp-calldata` in aescan to decode auth_data.
