### ISSUE TITLE
release workflow skips some of the changes

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/aescan#350]
### Context information

Some of the changes are missing when releasing a new version: https://github.com/aeternity/aescan/pull/347

Most likely the release-please action is using the latest released commit as a base, instead of latest minor change. 

NOTE: After fixing the workflow, adjust also the changelog of release 0.3.0 (and newer changelogs, if needed) to contain the full scope of changes

**Comment by lukeromanowicz** [comment]
Looks like we've got 2 options to resolve this:

A) in case of minor and major updates we should collect all the changes since the last minor update. Unfortunately, I faced some technical difficulties in making it work which can be tracked in this ticket: https://github.com/google-github-actions/release-please-action/issues/785

B) Force rebase the develop every time a patch update is released instead of merging it to maintain new changes order above previous release fixes - that might cause a lot of conflicts due to force changing git history. I think we should avoid this option

I'm open to any other suggestions. For now I will try to follow option A) hopefully with assistance from the Release Please maintainers

**Comment by janmichek** [comment]
No longer a problem
