### ISSUE TITLE
Improve Contract events arguments in account activities

### ISSUE THREAD

**Issue by janmichek** [aeternity/aescan#362]
### Describe the solution you'd like

- Decode known args (using the parameter aexn-args=true)
- Find a better way to print arguments that cannot be decoded? In my opinion in any case these should be printed somehow and explain to the user what should be done in order to decode them (Until we add contract verification)

**Comment by marc0olo** [comment]
@janmichek you mean the known AEX-9, AEX-141 and possibly also the DEX events, right?

as discussed yesterday I think we need to show the arguments in a more meaningful way.

I know for many it won't be possible until we have smart contract verification. but at least for the known events we should be able to do it already now

**Comment by michele-franchi** [comment]
Mdw reference: https://github.com/aeternity/ae_mdw/issues/1497

**Comment by janmichek** [comment]
@michele-franchi Can you link the initial requirements, please? The screenshot from Confluence with desired values to be printed

**Comment by janmichek** [comment]
Question raised in slack

**Comment by janmichek** [comment]
related https://github.com/aeternity/aescan/issues/512

**Comment by janmichek** [comment]
We have now the smart contract verification with event decoding published
