### ISSUE TITLE
Remove workaround of total token supply

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#37]
We used a temporary workaround because we could not wait for MDW fix

Once this https://github.com/aeternity/ae_mdw/issues/1244  will be merged and deployed we can revert workaround

**Comment by jyeshe** [comment]
Got a reply that aeknow supply is calculated based on the inflation curve, which is an approximation.

On genesis there wasn't 276450333 AE. It might have been the initial plan. 

The actual total mint sum is 276132594 AE and was distributed throughout these heights:
  {0, 89451376822397976634367408},
  {47800, 27051422546127651538826703},
  {90800, 72681157406723951132840970},
  {161150, 86948638040240004719633952}

So we know now the difference and you can use the /totalstats (:
