### ISSUE TITLE
ContractCallTx: delay in showing details

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aescan#374]
I just performed following tx:
- https://testnet.aescan.io/transactions/th_BydyNtqy5xKq3iYou1LfxTLxpN5hednLweta5xpayfhpVWgG9

although the middleware already delivered the missing information in the endpoint, the UI didn't serve the data. I am wondering about the logic on that page.

is the UI currently waiting for 1 confirmation before the actual details will be shown? to me it would be more a bug, but can also be seen as improvement 😁

**Comment by michele-franchi** [comment]
This will be solved by #466.
