### ISSUE TITLE
Research allowing of external content modification with a nice editor

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/aescan#378]
### Please describe the problem that your request should resolve.
Research the possibility of allowing the Marketing team to modify the text on the website without contacting developers (most likely using a headless CMS).

Requirements:
* Marketing can easily modify the text on the website (not the layout or components structure)
* The editor should support internalization

**Comment by janmichek** [comment]
Do we have some clue about how frequent the changes will be?
If it's gonna be often, then some CMS would make sense.
But why would we like to change it frequently? Most of the hint's content is timeless.
Currently, I think the most simplistic solution is to handover the changes from marketing to devs or instruct the marketing team to edit through GH

**Comment by lukeromanowicz** [comment]
The outcome of the research has been posted on the confluence page called "External aeScan content modification" for internal approval

**Comment by janmichek** [comment]
We concluded on not to implement it
