### ISSUE TITLE
Refactor snake_case to camelCase

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/aescan#385]
### Please describe the problem that your request should resolve.
In many places of the application we are using snake_case and camelCase interchangeably. Refactor snake_case to camelCase to unify things.

examples: 
![image](https://github.com/aeternity/aescan/assets/46789227/4d2567d4-556e-46c5-a3d9-1fb9925ca24a)
![image](https://github.com/aeternity/aescan/assets/46789227/2ff44810-c6d3-4b8c-ad1f-a0478caa5b71)

**Comment by lukeromanowicz** [comment]
I recommend implementing it after TypeScript and backing it up by creating dedicated interfaces or models

**Comment by janmichek** [comment]
This has already been resolved in old explorer. I will try to reuse the solution as a draft, and we can start from it
