### ISSUE TITLE
Improve search bar

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#39]
- If a valid hash is entered the user is redirected to the details page
- If an invalid hash is entered the user is redirected to the search results page and the specific "not found" panel is displayed. Example:

<img width="622" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/85ce14b0-533d-4752-90ca-6580e7995438">

- If a string like "abc" is entered (not a hash), the user is redirected to the search results page to display names and tokens results

The last two cases are handled here: https://github.com/aeternity/aescan/issues/210

**Comment by michele-franchi** [comment]
@janmichek In my opinion it should stay the same. In this iteration there isn't the dropdown filter.

**Comment by marc0olo** [comment]
@michele-franchi what would the dropdown filter be used for in a future iteration?

**Comment by michele-franchi** [comment]
@marc0olo to restrict search to a specific entity. There are different cases, for example let's say you type in the search bar `815834`, what does this represents? If we exclude hashes ideally it could be a name, a token or a block height.
Not super needed right now but it could improve the search UX.

**Comment by marc0olo** [comment]
> could be a name, a token or a block height

yes, that's true. but I would recommend to stick to names first (as it already is, right?) and wait for real feedback from users. to me this sounds like wasted effort at this point of time.

personally I wouldn't search for a keyblock height at all and for tokens we have a dedicated tokens page where the search / filter will be applied anyway, right?

**Comment by michele-franchi** [comment]
@marc0olo yes, I completely agree! That's why It got separated from the original idea 😄 
The search bar will still prioritise names.

**Comment by janmichek** [comment]
> * If a valid hash is entered the user is redirected to the details page
> 
>     * If an invalid hash is entered the user is redirected to the search results page and the specific "not found" panel is displayed. Example:
> 
> 
> <img alt="image" width="622" src="https://user-images.githubusercontent.com/11598532/260980971-85ce14b0-533d-4752-90ca-6580e7995438.png">
> 
>     * If a string like "abc" is entered (not a hash), the user is redirected to the search results page to display names and tokens results
> 
> 
> The last two cases are handled here: #210

By the definition it's how it currently works (in production)
![firefox_uH8qVDFi8P](https://github.com/aeternity/aescan/assets/15363559/32d2503c-44da-4d00-a92c-4285f1e8e111)

**Comment by michele-franchi** [comment]
@janmichek I don't think that's the case for 
- If a string like "abc" is entered (not a hash), the user is redirected to the search results page to display names and tokens results

or am I missing something?
