### ISSUE TITLE
Microblocks tab is visible when the keyblock is not mined

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#406]
### Context information

application version: 
device: 
browser: 
operating system: 

### Steps to reproduce
- Open a keyblock which is not mined

### What is expected?
The microblocks tab should be hidden.

### What is actually happening?

<img width="1411" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/5b42fc55-c59a-4e87-8cbb-e3aa2946b800">

**Comment by janmichek** [comment]
I already spotted this and will be fixed in here https://github.com/aeternity/aescan/pull/395
