### ISSUE TITLE
Transactions trend chart

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#415]
Display a transactions trend chart with the following filters:

Group by: Day, Week, Month
Time range: TBD

**Comment by danilosierrac** [comment]
I really like Coinbase approach to it. Clean, minimal, and single line so there is not much to do except change the view parameter without needing a new design for each.

![Image](https://github.com/aeternity/aescan/assets/7396728/b7770ad2-103a-4ff7-8400-75f2478d0d16)

**Comment by danilosierrac** [comment]
Added a screen with counter and the graph to Figma
