### ISSUE TITLE
Search field placeholder text is too long

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aescan#420]
### Context information

application version: I can't find it at https://aescan.io/
browser: Google Chrome@116

### Steps to reproduce
- open https://aescan.io/

### What is expected?
To see the whole placeholder text

### What is actually happening?
<img width="613" alt="Screenshot 2023-08-02 at 13 50 46" src="https://github.com/aeternity/aescan/assets/9007851/90659581-e280-484e-9672-130cffe4e60c">

**Comment by michele-franchi** [comment]
Instead of the current long text we can add as placeholder: "Search anything on aeScan"

**Comment by Liubov-crypto** [comment]
Fixed, LGTM
