### ISSUE TITLE
add LAEX (Lexon.org) token to the default tokens

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aescan#427]
### Describe the solution you'd like
I want to see the `LAEX` token (contractId: `ct_xtk8rSz9suPb6D6VLquyfVji25FcnFRDjn3dnn5mmvHsPiESt`) added to the default token list shown at https://aescan.io/tokens

### Additional context
- the token contract is currently not classified by the mdw, but this should be fixed early next week afaik (cc @jyeshe @sborrazas)

Please use following icon for the token:
![lexon-logo-black](https://github.com/aeternity/aescan/assets/8124114/433d361f-017d-4040-9918-9c58638352bf)

**Comment by lukeromanowicz** [comment]
@marc0olo does the token has its equivalent on testnet?

**Comment by marc0olo** [comment]
> @marc0olo does the token has its equivalent on testnet?

there are testnet deployments afaik. but they are irrevevant IMO

**Comment by michele-franchi** [comment]
As a temporary solution we will hardcode the contract to the list of "listed tokens".
