### ISSUE TITLE
Selecting GAMeta from the transaction type list displays nothing

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#43]
Steps to reproduce:

- Use an wallet with GAMeta transactions
- Select GAMeta from the list

GAMeta transactions are not displayed.

It’s fixed, waitng for DB resync.

Once we will see non-empty array here, its resoled

 https://mainnet.aeternity.io/mdw/v2/txs?direction=backward&limit=10&account=ak_2Bwyd2yaNF7SaguZ19TyxyRpa5ep3WW1mR27tHM3jcgffGgf81&type=ga_meta

**Comment by janmichek** [comment]
It looks resolved. The example was not correct tho

https://github.com/aeternity/aescan/assets/15363559/f6d018bf-a8e1-4100-b6ba-a9e0976ce4d5
