### ISSUE TITLE
link to token page for AEX-X classified tokens

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aescan#435]
### Please describe the problem that your request should resolve.
can't easily access the token page for an AEX-9 token from contract detail view
![image](https://github.com/aeternity/aescan/assets/8124114/f68cfb3e-bbd0-459d-874a-afc8bce7377b)

### Describe the solution you'd like
please provide a way to access the token page from the contract detail view in case it is classified as AEX-9 / AEX-141 (once the page exists)

### Is it already possible to achieve the same outcome in any other way? If so, how?
not really, as token search in token view is missing for unlisted tokens. more experienced users can copy the contractId and past it into the `/tokens/` url 😄

**Comment by michele-franchi** [comment]
Solution: add a new row with token image and symbol

**Comment by danilosierrac** [comment]
Hola! It could be a row or an icon like we did in the Token pages. Either way would look great.

**Comment by michele-franchi** [comment]
The problem of the first one is that you don't actually see the token symbol, which in my opinion could be misleading

**Comment by lukeromanowicz** [comment]
Do we implement the second option then?

**Comment by michele-franchi** [comment]
@danilosierrac I forgot to tag you
