### ISSUE TITLE
Improve SEO to score top search results

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#44]
Verify that Plausible is tracking from desired stages and domains, and is using company credentials.
Verify that Sentry is tracking from desired stages and domains, and is using company credentials.
Verify the page is properly indexed by the search engines and sitemap is recognized.

**Comment by janmichek** [comment]
When i google `æScan` or `aeScan`, still not getting any results directing to our app

**Comment by michele-franchi** [comment]
Check if æ symbol affects SEO and unify page titles


![Image](https://github.com/aeternity/aescan/assets/11598532/c9b45825-f09e-4698-9a78-57af0d7bb352)

**Comment by marc0olo** [comment]
![image](https://github.com/aeternity/aescan/assets/8124114/53e7d2cf-c090-45ed-99d9-bece365b3fc2)

**Comment by marc0olo** [comment]
I just tested with google and Tor (private mode) -> æScan.io first result

![image](https://github.com/aeternity/aescan/assets/8124114/d4dd34e4-bd99-4483-8056-83e441098085)

**Comment by michele-franchi** [comment]
For me it appears as first result only if I search "æScan" or "aescan.io" but not "aescan".

**Comment by marc0olo** [comment]
it is definitely strange behavior. I am not a SEO expert though, but I am wondering why it works as expected in private mode for me

**Comment by lukeromanowicz** [comment]
@janmichek I'm afraid we don't. Do you have any suggestions how to keep track of things to do/check before/after prod deployments?

CC: @michele-franchi

**Comment by janmichek** [comment]
We can use our private calendar or setting an issue to check again
