### ISSUE TITLE
Search bar dropdown

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#445]
The existing search bar should be improved in order to allow search by different entities.
A dropdown should be visible with the following options:
- All types
- Transactions
- Accounts
- Names
- Smart Contracts
- Tokens
- Oracles
- State channels
- Keyblock id
- Keyblock height
- Microblock id

If "All types" is selected:
- If a valid hash is entered the user is redirected to the details page
- If an invalid hash is entered the user is redirected to the search results page and the specific "not found" panel is displayed
- If a string like "abc" is entered (not a hash), the user is redirected to the search results page to display names and tokens results

If a specific entity is selected:
- If an hash entity is selected and a valid hash is entered the user is redirected to the details page
- If an hash entity is selected and an invalid hash is entered the user is redirected to the search results page and the specific "not found" panel is displayed
- If tokens or names is entered, the user is redirected to the search results page to display names or tokens results

To handle: hash symbol "#" in search propagates to url and causing undesired behaviour.

**Comment by janmichek** [comment]
We can close this, right? @michele-franchi

**Comment by michele-franchi** [comment]
@janmichek closing this.
