### ISSUE TITLE
Show names for known addresses

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aescan#451]
### Please describe the problem that your request should resolve.
There are "known" addresses that don't have associated AENS names and get shown currently just as addresses. It complicates the investigation of the transaction history.

### Describe the solution you'd like
For example, on aeknow.org
ak_dArxCkAsk1mZB1L9CX3cdz1GDN4hN84L3Q8dMLHN4v8cU85TF showed as 2miners (mining pool?)
ak_6sssiKcg7AywyJkfSdHz52RbDUq5cZe4V4hcvghXnrPz4H4Qg as gate.io

### Is it already possible to achieve the same outcome in any other way? If so, how?
To claim names for these addresses 🙃 but probably they won't do it

### Additional context
https://www.aeknow.org/address/wallet/ak_6sssiKcg7AywyJkfSdHz52RbDUq5cZe4V4hcvghXnrPz4H4Qg

<img width="730" alt="Screenshot 2023-08-16 at 15 39 32" src="https://github.com/aeternity/aescan/assets/9007851/26efbb0f-2c0f-4669-b401-fd644034c91b">

**Comment by marc0olo** [comment]
I think we have 3 different entities for accounts `SpendTx`:
- `ak_...` (default)
- `nm_...` (name hash)
    - I am actually not sure how this is currently handled within the tx-table, but I know that in the details the actual name `xy.chain` is resolved and that we also display the address (`ak_...` ) which was set for the name at the time of the tx. I think in the tx-table we already display `xy.chain`
- `gate.io` (known entity)

I think it it would be fine to show the actual name (AENS / known entity) in the tx tables.

the question then pops up how to deal with those "entity" names in the tx-detail page. I think for the AENS names we have it already implemented to be transparent with the AENS name and the corresponding `ak_...`

**Comment by davidyuk** [comment]
Other addresses I find in aeknow

**Exchanges**
ak_jgiBUko9fTwg5HQ8nHFoPbjR22TBcg9LK85qsv1mTkcjdszFa -- CoinEx
ak_6sssiKcg7AywyJkfSdHz52RbDUq5cZe4V4hcvghXnrPz4H4Qg -- Gateio
ak_3oCNr4upswn5sRVpqdpuiCwxqwRU1tok2xLjLLy9vjvYRdVNd -- MXC
ak_dMyzpooJ4oGnBVX35SCvHspJrq55HAAupCwPQTDZmRDT5SSSW -- WeTrue.io (not sure that it is an exchange)
ak_vKdT14HCiLCxuT3M7vf3QREyUbQTr1u6Pz49ba9EhaD6uDqWs -- Huobi
ak_dnzaNnchT7f3YT3CtrQ7GUjqGT6VaHzPxpf2efHWPuEAWKcht -- Binance
ak_wftXwsMheVNA33YWiYLqFNnSSDnYsV9ynqRSnZT8P3kgZG9bn -- Hotbit

**Miners and others**
ak_wM8yFU8eSETXU7VSN48HMDmevGoCMiuveQZgkPuRn1nTiRqyv -- WoolyPooly
ak_dArxCkAsk1mZB1L9CX3cdz1GDN4hN84L3Q8dMLHN4v8cU85TF -- 2miners
ak_9MsbDuBTtKegKpj5uSxfPwmJ4YiN6bBdtXici682DgPk8ycpM -- 2miners.solo
ak_2KAcA2Pp1nrR8Wkt3FtCkReGzAi8vJ9Snxa4PcmrthVx8AhPe8 -- BRI

Would be good also register contracts like Superhero tipping, dex

**Comment by michele-franchi** [comment]
Great suggestion and thanks for the list @davidyuk
