### ISSUE TITLE
show hint if AENS name is in revoked state

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aescan#454]
### Please describe the problem that your request should resolve.
When an AENS name is revoked actively or expires, it enters in a revoked state for a certain time period (not sure how long exactly, need to look up).

During this time period, an AENS name cannot be claimed again and currently this information is not exposed to the public.

### Describe the solution you'd like
IMO, aeScan should display a hint about the revoked state on following pages:
- Names (Tab: Expired)
- Name details

### Is it already possible to achieve the same outcome in any other way? If so, how?
no

### Additional context
n/a

**Comment by michele-franchi** [comment]
@marc0olo isn't this hint what you are suggesting?


![Image](https://github.com/aeternity/aescan/assets/11598532/89ab5113-eb9a-4fcf-9934-96d576eccab2)
