### ISSUE TITLE
Add release notes to aescan.io

### ISSUE THREAD

**Issue by dvdbak** [aeternity/aescan#459]
Hello,

It would be great to have the release notes page, like they are in GitHub available e.g. new changes, version aso.

Thanks,
David

**Comment by janmichek** [comment]
What do you think about this? https://github.com/aeternity/aescan/releases

**Comment by dvdbak** [comment]
The information on this page is enough, if it would be accessible from the footer would be nice.

**Comment by michele-franchi** [comment]
I think we could add the version and the link to the release note.
