### ISSUE TITLE
display account details if accounts owns tokens and has never been seen on the network

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aescan#460]
### Context information
account details are currently not displayed although the account owns AEX-9 tokens

### Steps to reproduce
visit https://aescan.io/accounts/ak_PXVUiBzByjNX4VSTmay18fjDwrkUnwFbyNTy3NBG55GLF6M3r

the account got AEX-9 tokens with this tx:
- https://aescan.io/transactions/th_hiZV7wpVAwxrpHMJ3E5VCwKJDRBb1pU73cLbZE1jBvUqQCume

the account owns AEX-9 tokens, see:
- https://aescan.io/tokens/ct_xtk8rSz9suPb6D6VLquyfVji25FcnFRDjn3dnn5mmvHsPiESt

![image](https://github.com/aeternity/aescan/assets/8124114/c89cd915-ac57-45d8-893b-9b1c790a226f)

### What is expected?
the account details as well as owned tokens should be displayed

**Comment by michele-franchi** [comment]
@marc0olo The problem is the account did not execute any transaction so it's not even returned by the node API: 
https://mainnet.aeternity.io/v3/accounts/ak_PXVUiBzByjNX4VSTmay18fjDwrkUnwFbyNTy3NBG55GLF6M3r

I will investigate.

**Comment by marc0olo** [comment]
the reason is clear to me. but aeScan needs to handle it somehow

**Comment by michele-franchi** [comment]
Solution: display tab and come up with a different sentence.
