### ISSUE TITLE
Store transaction page/cursor in url of accounts page

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aescan#462]
Use case: I'm going to look though some transactions of account at https://aescan.io/accounts/<address>.

- I'm not at the first page of Transactions
- navigating to specific transaction by its hash
- after checking its details I want to go back, pressing back button
- I see account page at the tx page instead of where I was before 🙁 

The solution would be to store page/cursor in url of accounts page, like
`https://aescan.io/accounts/<address>/transactions/57491215` (cursor's value from mdw)

**Comment by marc0olo** [comment]
in this case I'd like to bring up another pagination feature:
- "First" / "Last" buttons
