### ISSUE TITLE
display link to contract attached to generalized account

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aescan#471]
### Please describe the problem that your request should resolve.
I want to be able to navigate to the contract that is attached to the generalized account easily.

### Describe the solution you'd like
initially we discussed "labels" on different account pages and somehow we lack of these all over the place:
- account **CAN** also be:
    - oracle (if registered & active)
    - smart contract (if it belongs to a contract or if a generalized account is associated)
    - "special contract" (AEX-X token, ...)

not sure where and why that got lost in the redesign or in the backlog in general.

### Is it already possible to achieve the same outcome in any other way? If so, how?
yes, given following generalized account:
- https://testnet.aescan.io/accounts/ak_2NuE65yQFR4QWwkfeJMYf7VN1yuEUDYhmba3ov9KTyCnSLn31M

I can click on the API link to the node and see the contract id of the attached contract in the response when opening the link

### Additional context
![image](https://github.com/aeternity/aescan/assets/8124114/2bcbf5a2-c542-4772-829b-7969a21cd9bb)

**Comment by janmichek** [comment]
I understand how to display contract Id for the account that has been generalized. Such an information is coming from the node.

But how can I gain info that the account also has registered and active Oracle or a special contract. I can only do additional chained request to check if such an oracle/contract exists. Do we wen to go this way?
