### ISSUE TITLE
Add Smart Contract verified

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#495]
- The Smart Contract page should display the contract is verified

- There should be a section (probably a new tab) that displays information about the verified contract

- Compiler version, License fields should be visible

- Source code of the Smart Contract with navigation and syntax highlighting (inspired from https://contracts.aepps.com)

- Contract ACI section with option to export

- Contract Creation Code with switch to bytecode

**Comment by michele-franchi** [comment]
@danilosierrac https://etherscan.io/address/0x81939550369e10d035d2c3ddcd8e02e3c38b0f8b#code

**Comment by danilosierrac** [comment]
Got it! On it :)
