### ISSUE TITLE
Add custom date picker to transactions chart

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#499]
Add custom date picker to transactions chart, native browser date picker.

**Comment by janmichek** [comment]
UI is prepared, now waiting for extension of endpoint to be able to accept date range.
Moving this on hold
Tracking https://aeternity-workspace.slack.com/archives/C04K21DM61L/p1696322458020479

**Comment by janmichek** [comment]
also extend Contract Calls chart with this
