### ISSUE TITLE
Recipient/sender name not displayed

### ISSUE THREAD

**Issue by janmichek** [aeternity/aescan#511]
### Steps to reproduce
![firefox_jZzPdbgPwn](https://github.com/aeternity/aescan/assets/15363559/c6cd1460-0a8e-4d96-b460-0385f03e8324)

### What is expected?

there should be name instead of account id

**Comment by janmichek** [comment]
@michele-franchi this is apparently more of a general appeal.

As a user, I would expect the name to be displayed instead of the address in the app in almost every place. Such a pair of name and address should MDW serve. It only serves name and address in name-related responses. This needs to be requested from MDW team if we want to implement this feature?

**Comment by janmichek** [comment]
@michele-franchi ping

**Comment by michele-franchi** [comment]
Cannot be done because an account could have multiple AENS names attached.
