### ISSUE TITLE
New menu structure

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#617]
### Describe the solution you'd like

The menu should be adjusted to add new items, along with the existing ones:
- Top Accounts
- Verify Contract

should also take in consideration Wallet Connection and mobile view.

**Comment by janmichek** [comment]
Few notes for further implementation, after research of referenced solutions

- [ ] the mobile menu is collapsible and exclusive (only one can be open at time)
- [ ] seems like the simplest solution is to prepend menu over main content = no overlay. The overlay comes with a lot of problems as it is 2nd dimension of layout
- [ ] Desktop nad mobile menu seems to be too distinctive and 2 components would serve it better (currently we have 1)
- [ ] the wallet connection UI is placed out of the mobile menu (next to hamburger UI)
-
