### ISSUE TITLE
Display tokens owned in the account detail 

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#62]
### Please describe the problem that your request should resolve.
It's not possible to see tokens held by a specific account.

### Describe the solution you'd like
Account detail should display all tokens related to an account, with hints and loading state.
A new tab called "Tokens" should be added to the account details, with the following table:

| Symbol | Name | Contract | Quantity | Value
|--------|--------|--------|--------|--------|
| (ICON) WTT | WeTrue Token | ct_KeTvHnh...Yb | 695,014,369 | $2934.93

Value column could be empty.

### Is it already possible to achieve the same outcome in any other way? If so, how?
No

### Additional context

Example call: https://mainnet.aeternity.io/mdw/v2/aex9/account-balances/ak_2UGL6qArnbWx9fEkJyszssMkCjpu3VeLFBPA6MXYV3APfDSz1k

**Comment by danilosierrac** [comment]
I would love to know more about this. Should it be a counter?

**Comment by danilosierrac** [comment]
Working on this today
