### ISSUE TITLE
Name status misalignment

### ISSUE THREAD

**Issue by janmichek** [aeternity/aescan#621]
There are 2 problems with this

- [ ] the logic is distributed and duplicated on 2 places in the app in `formatNameStatus` and `NameDetailsPanel.vue`  This should be unified

tracking: https://github.com/aeternity/ae_mdw/issues/1767

https://github.com/aeternity/aescan/assets/69896204/16abfaa4-00a7-41b1-a062-47dbc7c28578

_Originally posted by @Liubov-crypto in https://github.com/aeternity/aescan/issues/609#issuecomment-1852297238_

**Comment by janmichek** [comment]
I could not replicate this issue again. Was the current status of mdw out of sync?

So we can proceed to refactoring, the logic is distributed on many places over the app

**Comment by Liubov-crypto** [comment]
> I could not replicate this issue again. Was the current status of mdw out of sync?
> 
> So we can proceed to refactoring, the logic is distributed on many places over the app

It's reproducible for me on prod, for example you can check name dincho.chain, please compare Ends blocks:


https://github.com/aeternity/aescan/assets/69896204/a67e874d-6186-478a-8e62-7c2af2ac8d6a

**Comment by janmichek** [comment]
> > I could not replicate this issue again. Was the current status of mdw out of sync?
> > So we can proceed to refactoring, the logic is distributed on many places over the app
> 
> It's reproducible for me on prod, for example you can check name dincho.chain, please compare Ends blocks:
> 2024-05-10.3.15.13.mov

yea, you are right thanks. Couls not verify on this example but found another ones

**Comment by janmichek** [comment]
Related to this https://github.com/aeternity/aescan/issues/794
