### ISSUE TITLE
If user look at the activity of the selected account, then in the third step the view will break

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/aescan#628]
If user look at the activity of the selected account, then in the third step the view will break. Reproducible on product: 
account: ak_11111111111111111111111111111111273Yts 

https://github.com/aeternity/aescan/assets/69896204/3d5d2b62-129b-4b3d-8f34-662318b4e153

![err](https://github.com/aeternity/aescan/assets/69896204/683c1d47-43bb-45a4-9153-032654ec8921)

**Comment by janmichek** [comment]
It's MDW related issue
Tracking https://github.com/aeternity/ae_mdw/issues/1653

**Comment by janmichek** [comment]
Quick consultation not regarding the issue
Mentioned account serves for burned tokens.
Should we also include this int translation of known addresses? What u think @michele-franchi

**Comment by janmichek** [comment]
Fixed by MDW.

However I found Aex141Transfer activity that has not been served by component. That's something I will fix here
