### ISSUE TITLE
Smart Contract Upload

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#642]
Acceptance criteria:
- Smart Contract ID, Compiler Version, License Type, and terms of service fields should be marked as required, according to design. Example:
<img width="771" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/0b7b78e8-a61a-43dd-8316-a4ae76ea91ee">

- Smart Contract Upload should allow files upload and should also keep the folder structure.

**Comment by janmichek** [comment]
Part of #253
