### ISSUE TITLE
Smart Contract "Contract" Tab

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#644]
Acceptance criteria:
- Create a tab called "Contract"
- If the contract is not verified:
  - Display a text that explains that the contract is not verified but the user can verify it by pressing a call to action button
- If the contract is verified:
  - Display the green checkmark next to the tab name
  - Display all files in a vertical way with the following title: "File 1 of 4: lib/hello.aes"
  - The code should have syntax highlighting (inspiration from https://contracts.aepps.com/)
  - Two sections should be added: Contract creation code and ACI

**Comment by janmichek** [comment]
part of https://github.com/aeternity/aescan/issues/495
