### ISSUE TITLE
Some names are present in 2 tabs Expired and In Auction

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/aescan#654]
### Context information

application version: pre-release branch [498cda6](https://github.com/aeternity/aescan/pull/652/commits/498cda6e79728054f8061a468e2dd62b95fc1759)

browser:  Firefox 121
operating system: MacOS

### Steps to reproduce
1. Open Names list 
2. Check some name for example 77.chain
3. Name will be present in 2 tabs and statuses: Expired and In Auction

### What is expected?
Should be in 1 condition - expired or in auction

**Comment by janmichek** [comment]
Known issue https://github.com/aeternity/aescan/issues/621
