### ISSUE TITLE
smart contracts event decoding

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#669]
The Smart Contract verification now allows to decode events of smart contracts in the following table: https://aescan.io/contracts/ct_9cYQVU42y1icb9VEGijUs93xyTbKwmq4d7JhdnTYPZ7rMQhwz?type=events

A research should outline what can be decoded from the logs endpoint, used in the smart contracts event table:
https://mainnet.aeternity.io/mdw/v2/contracts/logs?contract_id=ct_9cYQVU42y1icb9VEGijUs93xyTbKwmq4d7JhdnTYPZ7rMQhwz&aexn-args=true

**Comment by janmichek** [comment]
related https://github.com/aeternity/aescan/issues/362
