### ISSUE TITLE
migrate names related endpoints to v3

### ISSUE THREAD

**Issue by janmichek** [aeternity/aescan#690]
### Please describe the problem that your request should resolve.
Use data resources from new version of MDW

### Describe the solution you'd like
 ON HOLD
Bid count missing https://github.com/aeternity/ae_mdw/issues/1916
missing status https://github.com/aeternity/ae_mdw/issues/1954

In the following parts these should be done

TODO IMPROVE DESCRIPTION HERE

- [x] aex141 related (exposed in v3 but not migrated) https://github.com/aeternity/ae_mdw/issues/1898
- [x] aex9 related (exposed in v3 but not migrated)
- [x] contracts/logs
- [x] txs/count (reported bug in Slack)

### Additional context
https://petstore.swagger.io/?url=https://mainnet.aeternity.io/mdw/v3/api

It is expected as a more ongoing process. Will be probably separated into multiple PRs. Collaboration with mdw team will be needed

**Comment by janmichek** [comment]
v3/statistics/transactions endpoind can be filtered by tx_type. Do we want to incorporate this? @michele-franchi

**Comment by janmichek** [comment]
There is a `type_group` in /transactions
Not sure how could we utilize this

**Comment by michele-franchi** [comment]
@janmichek to check if additional endpoints can be migrated to v3.

**Comment by janmichek** [comment]
New name search endpoint added
https://github.com/aeternity/ae_mdw/issues/1651#issuecomment-2194488509
This will also resolve the search case sensitivity

**Comment by janmichek** [comment]
Possible resolution of counters.
To check: https://github.com/aeternity/ae_mdw/issues/1816#issuecomment-2194528015

**Comment by janmichek** [comment]
Remove `expand=true` 
To check https://github.com/aeternity/ae_mdw/issues/1018#issuecomment-2194507399

**Comment by janmichek** [comment]
- [ ] To check fee naming
https://github.com/aeternity/ae_mdw/issues/1818#issuecomment-2186261341

**Comment by janmichek** [comment]
- [ ] to check usage pointers in v3 
https://github.com/aeternity/ae_mdw/issues/1425#issuecomment-2194500524

**Comment by janmichek** [comment]
only names related endpoints are missing to migrate from now

**Comment by janmichek** [comment]
Check no usage of expand true https://github.com/aeternity/ae_mdw/issues/1018

**Comment by janmichek** [comment]
check name fee vs fee https://github.com/aeternity/ae_mdw/issues/1818
