### ISSUE TITLE
Blocks chart page

### ISSUE THREAD

**Issue by janmichek** [aeternity/aescan#696]
**Acceptance criteria:**
- A new page called "Charts" is visible in the top menu
- A left navigation bar is visible in the page with a clickable item "Blocks"
- The right side of the page contains a chart with blocks data
- At the top of the chart:
  - Time interval controls are visible
  - A dropdown to select the resolution is visible with the following values: 1 Day, 1 Week, 1 Month
- The default interval of the chart is the last year with a resolution of 1 day 

Mdw endpoint: https://mainnet.aeternity.io/mdw/v3/statistics/blocks

**Comment by janmichek** [comment]
@michele-franchi do we wanna accomodate this https://github.com/aeternity/aescan/issues/689 here ?

**Comment by michele-franchi** [comment]
@janmichek IMO should be done separately, I'll think about it
