### ISSUE TITLE
Transaction not found page is empty

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aescan#726]
### Context information
browser: Chrome 123

### Steps to reproduce
- navigate to https://aescan.io/
- type into search box "th_2muLsbZeFaVJ3tePTnLqobPhxBzwFsm1zUv8sjgMX4LKuevX2T"
- hit Enter
- see white screen

### What is expected?
To have some text about missed transaction 🤷‍♀️ 

### What is actually happening?

<img width="1425" alt="Screenshot 2024-04-15 at 22 31 00" src="https://github.com/aeternity/aescan/assets/9007851/db7ee2db-774e-4b42-b3eb-ceaa022b6dc6">

**Comment by janmichek** [comment]
This has already been reported and resolved here https://github.com/aeternity/aescan/issues/674 and it's waiting for deployment. 
You can check the functionality here https://aescan.dev.service.aepps.com/
