### ISSUE TITLE
The full file path is not visible when Contract Files are uploaded

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#728]
### Context information

application version: 
device: 
browser: 
operating system: 

### Steps to reproduce
- Navigate to /contract-verification page
- Drag and drop a file and a folder with another file in it

### What is expected?
The full file path is displayed. For example if I drag and drop the following structure:
- hamster.aes
- lib/hamster_utils.aes

the following should be displayed:
<img width="637" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/2920d2ac-4136-493f-845b-0a141f0a0de5">

### What is actually happening?

Only the file name is displayed:
<img width="616" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/59944b52-fd63-4e2e-8e45-24c70c4d7b6f">

**Comment by janmichek** [comment]
Could you provide more details, please? @michele-franchi 
The way you describe it, seems to work. I try some other similar ways, but seems to work pretty solid.

https://github.com/aeternity/aescan/assets/15363559/77635be3-a5f7-4dbf-bcb9-552c644cf616
