### ISSUE TITLE
Raw data pointer support for Ceres

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#733]

**Comment by janmichek** [comment]
@michele-franchi Can you provide more information about it, please?

**Comment by janmichek** [comment]
https://github.com/aeternity/ae_mdw/pull/1708

**Comment by janmichek** [comment]
@michele-franchi do you have some findings about this?

**Comment by michele-franchi** [comment]
@janmichek here's an example of raw data pointers I created:
https://testnet.aeternity.io/mdw/v2/names/testaensrawpointers.chain

with the following NameUpdateTx:
```
    const nameUpdateTx = await sdk.aensUpdate(name, {
        Pointer1: encode(Buffer.from('example data for pointer 1'), Encoding.Bytearray),
        Pointer2: encode(Buffer.from('example data for pointer 2'), Encoding.Bytearray),
        Pointer3: encode(Buffer.from('example data for pointer 3'), Encoding.Bytearray),
        Pointer4: encode(Buffer.from('example data for pointer 4'), Encoding.Bytearray),
    });
```

As you can see these pointers are not decoded in different places:

- Name details, custom pointers (notice the wrong pointer name, there's a comma at the beginning?):
![Image](https://github.com/aeternity/aescan/assets/11598532/2c2394ad-e6bd-4054-b8d3-7f66807d1be4)

- Account details, names tab:
![Image](https://github.com/aeternity/aescan/assets/11598532/0b874a2e-00b4-48f2-b10d-54da2e28c118)

Custom pointers should be plain text if the value is not a valid blockchain entity. In a custom pointer I can add any string value.

Example mdw call: https://testnet.aeternity.io/mdw/v2/names/testaensrawpointers.chain
