### ISSUE TITLE
AE coin details

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#749]
**Acceptance criteria**:
- A new page is visible displaying AE coin information (/tokens/AE)
- A panel is visible with the following data:
  - Symbol: AE (+ logo)
  - Price: AE ($) with also percentage change (same as dashboard)
  - Total Supply
  - Circulating Supply
  - Decimals
- Each row of the panel has tooltips

**Comment by michele-franchi** [comment]
Exchanges:
Exchange #1 - @gate_io 🔗 [mexc.com](http://mexc.com/)
Exchange #2 - @MEXC_Official 🔗 [mexc.com](http://mexc.com/)
Exchange #3 - @CoinstoreExc 🔗 [coinstore.com](http://coinstore.com/)
Exchange #4 - @HotcoinGlobal 🔗 [hotcoin.com](http://hotcoin.com/)
Exchange #5 - @CoinWOfficial 🔗[coinw.com](http://coinw.com/)

**Comment by janmichek** [comment]
1) is the hardcoded decimals good enough solution
2) Where should be a link to navigate to such a page? @michele-franchi
