### ISSUE TITLE
Tokens search case sensitivity

### ISSUE THREAD

**Issue by janmichek** [aeternity/aescan#757]
### Context information
Just a tracking of https://github.com/aeternity/ae_mdw/issues/1549 on our side
Check after implementation

### Steps to reproduce
there is a difference is search of `wrapped` and `Wrapped`
https://aescan.io/search/Wrapped?type=tokens
https://aescan.io/search/wrapped?type=tokens

### What is expected?

should return same result

**Comment by michele-franchi** [comment]
@janmichek To check if it works as expected, after the mdw releases it.

**Comment by janmichek** [comment]
Soleved on MDW side
