### ISSUE TITLE
Document ENV variables of container

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aescan#777]
In general, they are not explained, I need to know which is required. For example, `APP_DOMAIN` is used only in analytics, so it is not required.

https://github.com/aeternity/aescan/blob/ed2c604e47c16fd7a3711645a454c8b1c9a389a6/.env.example#L3

This one seems unused.

Additionally, I propose adding reasonable defaults like connecting to the mainnet out of the box.

**Comment by janmichek** [comment]
Significantly improved .]
