### ISSUE TITLE
Improve transaction detail type design

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#79]
Problem:

SpendTx type has AENS info in header, on the same line with title
![image](https://user-images.githubusercontent.com/11598532/232038683-288b75b7-8368-4adb-ba99-ec162182b753.png)

When SpendTx is an inner transaction of PayingForTx, only table content is reused, so this info will be omitted. Also this place is occupied.
![image](https://user-images.githubusercontent.com/11598532/232038727-6a19c7ac-039c-4906-98bd-c1b2edc54402.png)

Suggested solution

Move the Name label completely to table like this:
 
![image](https://user-images.githubusercontent.com/11598532/232038791-7a76a663-dcfa-4ed6-bf29-0972bb0e9ffc.png)

Personally, I don’t feel like the Title and Name label belong on the same line (as on first image).

**Comment by janmichek** [comment]
OUtdated
