### ISSUE TITLE
Call transaction missing in contract overview

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aescan#798]
Hey, inside `events` a transaction is properly listed: 

<img width="1286" alt="image" src="https://github.com/aeternity/aescan/assets/11761828/0b6be3b3-244d-4c4f-9986-6ea8535cc8b9">
( https://aescan.io/transactions/th_9hsJzzrx67y17ue7vKK7kyyi9hoYgCvaYqBe9sZBe998hR5pq )

but in the `call transactions` it is missing: 
<img width="1320" alt="image" src="https://github.com/aeternity/aescan/assets/11761828/3e6769ff-db2c-4f09-b510-8a9fecbccba8">

This is the contract: https://aescan.io/contracts/ct_2AiMceYFXnUdA6A9Lu2ZQ2tr2TpfbGVfkxLfBnceoWgHTKZYvc?type=call-transactions 

Feel free to move to MDW if it's an MDW issue of course. Thanks a lot guys.

**Comment by janmichek** [comment]
Moved here https://github.com/aeternity/ae_mdw/issues/1925
