### ISSUE TITLE
UI readability followup 

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#820]
Followup of #397.

What can be further improved:
- [x] Transaction details panels are not aligned on mobile:
<img width="564" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/22364b94-c7ac-47ff-a0df-e2c350faf1db">

- [x]  Name details special pointers tooltips are not left aligned:
<img width="1305" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/c4acf3d3-5ed7-49f7-8ebc-f72e65f99a82">

- [x] Name details special pointers are not aligned to the name details panel:
<img width="1372" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/c1fd6901-7600-402c-9935-c34a0f1d9d66">

- [x]  On mobile token events have a typo "arguemnts":
<img width="424" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/ea380e21-9330-4910-b63a-1e7816aacf0b">

- [x]  Oracle events tooltips are not left aligned:
<img width="433" alt="image" src="https://github.com/aeternity/aescan/assets/11598532/ac41cc67-22d7-40c2-900d-377b9462c4d0">

- [x]  Token details page links do not have spacing:
![Image](https://github.com/aeternity/aescan/assets/11598532/1c29a0bb-5b37-402b-bbdd-85a28aa9fcbf)

**Comment by janmichek** [comment]
The PR is still open there https://github.com/aeternity/aescan/pull/717
Should I implement it in there? @michele-franchi

**Comment by michele-franchi** [comment]
@janmichek I will have a final look at #717, merge it and then proceed with this followup otherwise #717 becomes very huge and hard to check (which is already).

**Comment by janmichek** [comment]
> * Name details special pointers are not aligned to the name details panel:

I am no quite sure what you mean by this. I cannot see it from the attached image

**Comment by janmichek** [comment]
> Transaction details panels are not aligned on mobile:

Well this is the screenshot from the mobile view where the column width is decided automatically
