### ISSUE TITLE
AE coin markets

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#822]
**Acceptance criteria:**
- A new tab is visibile in the AE coin page called "Markets"
- Inside the tab a table is present with the following columns:
  - Exchange name
  - Token pair
  - Price
  - Volume (24h)
- Data is cached, some endpoints cannot be filtered
- Price and Volume are expressed in $

API Endpoints:
- Gate.io API: https://api.gateio.ws/api/v4/spot/tickers?currency_pair=AE_USDT
- Mexc: https://api.mexc.com/api/v3/ticker/24hr?symbol=AEUSDT
- Coinstore: https://api.coinstore.com/api/v1/market/tickers
- Hotcoin: https://api.hotcoinfin.com/v1/market/ticker
- CoinW API: https://api.coinw.com/api/v1/public?command=returnTicker

**Comment by janmichek** [comment]
@michele-franchi it's not super-clear to me what price from response should be displayed.
Is it the `low`, `high`, `last`, `buy`, `sell` ? Or should there be further calculation on frontend?

**Comment by michele-franchi** [comment]
@janmichek the last price

**Comment by janmichek** [comment]
> @janmichek the last price

The response from CoinStore https://api.hotcoinfin.com/v1/market/ticker is following

![image](https://github.com/aeternity/aescan/assets/15363559/1ea0eaca-e88c-4f55-82aa-bc0732345778)

There is no last price or value similar to it.

How should I resolve it? @michele-franchi ?

**Comment by janmichek** [comment]
> > @janmichek the last price
> 
> The response from CoinStore https://api.coinstore.com/api/v1/market/tickers is following
> 
> ![image](https://private-user-images.githubusercontent.com/15363559/338582465-1ea0eaca-e88c-4f55-82aa-bc0732345778.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxMTMyNjUsIm5iZiI6MTcxODExMjk2NSwicGF0aCI6Ii8xNTM2MzU1OS8zMzg1ODI0NjUtMWVhMGVhY2EtZTg4Yy00ZjU1LTgyYWEtYmMwNzMyMzQ1Nzc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDEzMzYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzMTVlZDE1NmMwMzdlMDE4MDNlNTU3NTA0MjRiNWVkYjZiYTI0YTcwMWVlMDIwNTZkNDdjMTgzMTYyMGFmZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tdRYXWi7-4mTr4aXFZsyB327b2PQR2nSz8YvsqXhnB4)
> 
> There is no last price or value similar to it.
> 
> How should I resolve it? @michele-franchi ?

I found it in their docs. It's a 'close' value. But still seems to be unreasonably high.
