### ISSUE TITLE
Active accounts chart

### ISSUE THREAD

**Issue by janmichek** [aeternity/aescan#863]
### Describe the solution you'd like
"Active" is considering a specific time frame (daily), not overall.
For each day it should be visible the following: unique addresses that were active on the network as a sender or receiver.
- [x] also print latest value in https://aescan.io/tokens/AE with a hint
- [x] add some small refactoring, styles template or interact,...

### Additional context

https://mainnet.aeternity.io/mdw/v3/stats/active-accounts?interval_by=week&limit=10

**Comment by janmichek** [comment]
How to determine 'active @michele-franchi '

**Comment by michele-franchi** [comment]
Unique addresses that were active on the network as a sender or receiver.

**Comment by janmichek** [comment]
Yes, but we need to set some threshold after which is the account considered as inactive.
Or just single transaction from some account makes it active forever?

**Comment by michele-franchi** [comment]
"Active" is considering a specific time frame (daily), not overall.
For each day it should be visible the following: unique addresses that were active on the network as a sender or receiver.
