### ISSUE TITLE
Handle 500 errors

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#87]
500 errors should be handled to not display the default 500 error Nuxt page, for example:

https://aescan.dev.aepps.com/transactions/th_QRAjvukXobteRXCFzZZtA23iNJTiqpX5LxZN4nhdD6vUPG96X

We need a 500 Internal Server Error page, skip illustration for now.

**Comment by danilosierrac** [comment]
Added a very basic first proposal for the 500 in the search not found section
