### ISSUE TITLE
Improve ACI formatting/rendering

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aescan#899]
Currently it looks like

<img width="859" alt="Screenshot 2024-08-28 at 13 13 01" src="https://github.com/user-attachments/assets/45e20130-7de8-4beb-b5c2-2c664d4cb4f8">

at https://testnet.aescan.io/contracts/ct_HzBhnwxXg2zsPAmpX6ppoJNA5q1oojn8ZL2AsWozRxuBFERWD?type=contract-verified

Firstly you can add indents using `JSON.stringify(data, null, 2)`. This would improve readability significantly.

Would be best to visualize it with its own ui, in a fashion of swagger docs.
https://testnet.aeternity.io/mdw/swagger/

**Comment by janmichek** [comment]
This suppose to be the raw input. The thing that you pointed on is currently under review and will be delivered soon.
https://github.com/aeternity/aescan/pull/872
