### ISSUE TITLE
Firefox CSP issue

### ISSUE THREAD

**Issue by michele-franchi** [aeternity/aescan#9]
### Context information

application version: 
device: 
browser: 
operating system: 

### Steps to reproduce

Firefox gives different CSP errors in the console.

### What is actually happening?

![image](https://user-images.githubusercontent.com/11598532/229573308-fe7d250b-a23b-46ef-af49-f4c1f031cd0c.png)

**Comment by janmichek** [comment]
Probably caused by some extension. It's not a problem in incognito mode. And id doesn't have any negative effect even with extensions
