### ISSUE TITLE
Don't require compiler version in verification

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aescan#900]
<img width="229" alt="Screenshot 2024-08-28 at 13 33 28" src="https://github.com/user-attachments/assets/83835c40-7d5e-47e7-b03e-304e75004e26">

at https://testnet.aescan.io/contract-verification
Compiler version can be extracted from bytecode by

```js
calldata = require('@aeternity/aepp-calldata')
c = new calldata.ContractEncoder()
// https://testnet.aeternity.io/v3/contracts/ct_HzBhnwxXg2zsPAmpX6ppoJNA5q1oojn8ZL2AsWozRxuBFERWD/code
c.decode('cb_+JZGA6ChqMLv4ude/7H99pvMlDnAZQsLIJfYj6/C+eGDo2o9NMC4abP+RNZEHwA3AQc3ABoGggABAz/+boPhzgA3AQcHFiQAggD+rjHQWQA3AQc3ABoGggABAz+xLwMRRNZEHxFpbml0EW6D4c5BbXVsdGlwbHlCeUZhY3RvchGuMdBZJXNldEZhY3RvcoIvAIU3LjQuMAD9z2HE').compilerVersion
// '7.4.0'
```

This would make easier to verify a contract.

**Comment by janmichek** [comment]
Thanks, it's already here https://github.com/aeternity/smart-contract-verifier/issues/53
