### ISSUE TITLE
Support compilers 8.0.0, 8.0.1 in verification

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aescan#901]
<img width="229" alt="Screenshot 2024-08-28 at 13 36 48" src="https://github.com/user-attachments/assets/3cc44dee-d1ae-443e-a35f-7e850a652dab">

The newest compiler I can find in the list is 7.4.1, but [8.0.1](https://github.com/aeternity/aesophia/releases/tag/v8.0.1), [8.0.0](https://github.com/aeternity/aesophia/releases/tag/v8.0.0) have been released since then.

**Comment by janmichek** [comment]
Duplicate here https://github.com/aeternity/smart-contract-verifier/pull/57
