### ISSUE TITLE
Share verified status with all contracts with the same bytecode

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aescan#905]
I have two contracts with the same bytecode
https://testnet.aescan.io/contracts/ct_HzBhnwxXg2zsPAmpX6ppoJNA5q1oojn8ZL2AsWozRxuBFERWD
https://testnet.aescan.io/contracts/ct_2STMZW3uEs752isQdEihVW1Teq1XfAKWWZhazJMRcDKLa6iRcD
one of them is verified, but the other is not. I think aescan can show both of them as verified because the bytecode is the same.
https://testnet.aeternity.io/v3/contracts/ct_HzBhnwxXg2zsPAmpX6ppoJNA5q1oojn8ZL2AsWozRxuBFERWD/code
https://testnet.aeternity.io/v3/contracts/ct_2STMZW3uEs752isQdEihVW1Teq1XfAKWWZhazJMRcDKLa6iRcD/code

**Comment by janmichek** [comment]
Good idea, just moved it here
