### ISSUE TITLE
strange token price

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aescan#939]
Hey, I see some strange price displayed for this random token here, which should not be traded anywhere I think - where does that dollar value come from ? 

<img width="1022" alt="image" src="https://github.com/user-attachments/assets/352ca156-dd6c-43a3-ad87-9b12fcca8cbf">

It can be found here: https://aescan.io/accounts/ak_uTWegpfN6UjA4yz8X4ZVRi9xKEYeXHJDRZcRryTsRHAFoBpLa?type=tokens

**Comment by janmichek** [comment]
Hello, the value comes from Dex. It does not seems kinda right. I am not sure what is your expectation. Would be helpful if you fill the Bug report template

**Comment by nikita-fuchs** [comment]
Hey, I didn't fill out the bug report template because I do not know what the correct/expected behaviour would be - I guess just not displaying anything at all then? What did you have in mind ?

**Comment by janmichek** [comment]
The values are wired to DEX, so if there is a value it will be printed as it is here.
The token looks like wrapped AE Coin
If you are not satisfied with the value itself, that's something that you can resolve with dex.
