### ISSUE TITLE
Can't load contract details:

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aescan#967]
Hey, opening https://aescan.io/contracts/ct_2Xdym95f2i998W9Zoh1NgAB7pVuQ34ztEsema7u4XwSoq5VKUJ?type=call-transactions

the console throws me the error: `TypeError: Cannot read properties of null (reading 'contractId')` and after displkaying the information for a split second, everything is gone again.

**Comment by janmichek** [comment]
Thanks for reporting, will take a look
