### ISSUE TITLE
Implement counter for token Holders

### ISSUE THREAD

**Issue by lukeromanowicz** [aeternity/aescan#98]
### Please describe the problem that your request should resolve.
When task https://github.com/aeternity/ae_mdw/issues/1257 is released in the MDW we should be able to add pagination information to the token holders table on token details page.

**Comment by janmichek** [comment]
Seems to be resolved. Can you help me to confirm @lukeromanowicz ?
If so, please close the issue right away.


https://github.com/aeternity/aescan/assets/15363559/0e8cc3c3-ae55-4b2a-95d2-bf4edb1935ed

**Comment by janmichek** [comment]
Aha, I was wrong. I guess its not resolved. The issue is about `counter`, right?

**Comment by lukeromanowicz** [comment]
@janmichek correct, it's about the counter above the table :+1:

**Comment by michele-franchi** [comment]
@janmichek to check the status of this issue.
