### ISSUE TITLE
Wallet connection is stop working 

### ISSUE THREAD

**Issue by Liubov-crypto** [aeternity/aescan#994]
After I connected wallet on prod it's stop working from time to time. Connection was lost. 

application version: production
device: macbook
browser: Firefox 132.0.2 (64-bit)
operating system: macOS

1. Connect wallet to aescan
2. Observe

Wallet was disconnected. 

https://github.com/user-attachments/assets/958e3dae-cf15-4ae6-9a89-41b119fde0cc

![scan](https://github.com/user-attachments/assets/5924a64b-bdb4-4fa9-8276-b35952be7ea6)

**Comment by janmichek** [comment]
@Liubov-crypto Can you check the same on https://aescan.dev.service.aepps.com/

There is the newer version of dependecies including sdk wallet upgrade you helped testing with last week. 
So maybe the new version on dev aleready solved it. Please let me know

**Comment by Liubov-crypto** [comment]
> @Liubov-crypto Can you check the same on https://aescan.dev.service.aepps.com/
> 
> There is the newer version of dependecies including sdk wallet upgrade you helped testing with last week. So maybe the new version on dev aleready solved it. Please let me know

With new version it's working as expected. 


https://github.com/user-attachments/assets/1e0e200b-13c8-41e5-8a86-c3233c5a6f0e

**Comment by janmichek** [comment]
Yeah, I thought this might help .] Thanks! Closing this then
